### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#10]
I was looking at the source files and they don't seem to include a license. Has it been chosen yet? If not, I think it would be a good idea to do so as it's a requirement for many companies.

**Comment by mpeltonen** [comment]
You're right. I've been thinking to use the same license as sbt (New BSD), but haven't gotten around to including it yet... Will do soon.

**Comment by ijuma** [comment]
Thanks!

**Comment by mpeltonen** [comment]
Added.
