### ISSUE TITLE
Recognise src\it as a test directory

### ISSUE THREAD

**Issue by jonfreedman** [mpeltonen/sbt-idea#100]
It would be nice to mark src\it\scala src\it\java and src\it\resources as test sources as per the project structure in https://github.com/harrah/xsbt/wiki/Testing

It would also be nice to not mark directories which do not exist as sources (i.e. src\main\java in a pure scala project)

**Comment by mpeltonen** [comment]
Integration test directories are now supported in latest snapshot, see https://github.com/mpeltonen/sbt-idea/pull/121

**Comment by ijuma** [comment]
Great! When are you planning to release an updated version of sbt-idea.

**Comment by mpeltonen** [comment]
Heh, I'd better not make any promises looking in the past :) But hopefully soon...
