### ISSUE TITLE
0.11.0 does not work with IntelliJ Nika EAP

### ISSUE THREAD

**Issue by tonit** [mpeltonen/sbt-idea#101]
Appearingly, running gen-idea and trying to open the project in IntelliJ Nika EAP (latest) results in Intellij not recognizing the folder as an Idea project (actually doing nothing).
This may be a change in .idea descriptors or an incompatibility in idea-sbt. 
The project opens flawlessly in IntellJ 10.5.2 (latest stable).

**Comment by ijuma** [comment]
A note: I've used Nika EAP on a project generated by sbt-idea with no issues.

**Comment by tonit** [comment]
Then maybe its a false assumption by me on how to use the plugin:
1. git clone a project. Lets say, akka from Github
2. sbt gen-idea
3. Try open project in Intellij

Could be an issue with akka specifics ..

**Comment by miguel-negrao** [comment]
the plugin works with sbt 0.11 and intellij Nika latest for me...

**Comment by mpeltonen** [comment]
I haven't had time to test Nika yet, but it seems we have differing views if it works or not.

**Comment by leepa** [comment]
In Idea 11 - the folder is not recognised as a project for me either.

**Comment by jrwest** [comment]
Just upgraded to IDEA 11 without issue. However, the projects I have tested are relatively small w/ not a lot of dependencies.

**Comment by ghost** [comment]
1) gen-idea
2) import existing project (directory structure)
3) re-run gen-idea

**Comment by thoraage** [comment]
Same problem here; on fresh projects. Older projects however seem to do alright. Dare not delete any idea-files anymore.

**Comment by ghost** [comment]
Guys,

This is what worked for me:
1. used the plugin to generate .idea and .idea_modules
2. moved aside the 2 folders as idea-sbt and idea_modules-sbt
3. use Nika IDE to generate a "new project from sources"
4. close IDE
5. mv idea-sbt/modules.xml .idea
6. mv idea_modules-sbt .idea_modules
7. re-generate with sbt-idea plugin
8. open IDE

**Comment by thoraage** [comment]
Great, that worked for me too. I also see that it is possible to open a fresh project through the recent projects list.

**Comment by fatlazycat** [comment]
Having an issue using the FSC with 11.02 and a sbt-idea project. Just get internal compiler error exit code -1. Fine if I turn off FSC. Any ideas ? I can get the FSC to work with a non sbt-idea generated project.

same project is fine on OSX, problem appears windows based.

Turns out to be running with a 64 bit jvm under windows causes the issues. Back to a 32 bit one and all is fine.

Thanks

**Comment by dwijnand** [comment]
@yaptv's workaround should be documentated somewhere.. I was only able to find this again because I happened to remember that he renamed the .idea_modules .idea_modules-sbt and was able to google for that and find this page again..

**Comment by mpeltonen** [comment]
Closing this as the plugin has been working quite well for several people with Idea 11.
