### ISSUE TITLE
Check for Continuations plugin and add it to the compiler plugins pane

### ISSUE THREAD

**Issue by miguel-negrao** [mpeltonen/sbt-idea#102]
When using the continuations plugin by placing this in build.sbt:

```
autoCompilerPlugins := true

addCompilerPlugin("org.scala-lang.plugins" % "continuations" % "2.9.1")

scalacOptions += "-P:continuations:enable"
```

The the compiler continuations plugin jar at ~/.ivy2/cache/org.scala-lang.plugins/continuations/jars/continuations-2.9.1.jar should be added to the "Compiler Plugins" pane in “Project Structure” -> “Modules” ->”Scala”  and the "Enable Continuations" option should be enabled in "Compiler Options".  If this is not done the project will not compile in Intellij IDEA.

This is what the start of the .iml file looks like after I manually enabled continuations:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="FacetManager">
    <facet type="scala" name="Scala">
      <configuration>
        <option name="compilerLibraryLevel" value="Project" />
        <option name="compilerLibraryName" value="scala-2.9.1" />
        <option name="continuations" value="true" />
        <option name="fsc" value="true" />
        <option name="pluginPaths">
          <array>
            <option value="$USER_HOME$/.ivy2/cache/org.scala-lang.plugins/continuations/jars/continuations-2.9.1.jar" />
          </array>
        </option>
      </configuration>
    </facet>
  </component>
```

**Comment by mslinn** [comment]
Continuations enablement in the SBT project are still not passed to the generated IDEA project.

**Comment by mpeltonen** [comment]
This should now work with the latest snapshot (1.4.0-SNAPSHOT).
