### ISSUE TITLE
gen-idea seems unresponsive

### ISSUE THREAD

**Issue by pawelprazak** [mpeltonen/sbt-idea#106]
After using eclipse plugin, sbt-idea looks slow.

In directory with existing project it stays at:
`[info] Trying to create an Idea module default-047fd2`

And in fresh dir it stucks at:
`[info] Trying to create an Idea module default-b6068b
[info] Updating {file:/home/pawel/Dropbox/src/scala/test/raid-simulator/}default-b6068b...
[info] Done updating.`

and it stays for a LONG time. I thought it just hanged. 

There should be more info for  the user, like:
`Downloading: .....................................                 34%   0 kb/s
`

Or something simpler, but the thing is to notify the user what's going on. 
`I'm working, be patient` or `Your network is slow, it may take some time, grab a coffee` ;)

Without it there is a lot of confusion, especially the first time, like:
"is it working?, it crashed?, is may internet connection failing? am I downloading some huge file that I forgot or maybe system is fetching updates?"

I hope you know what I mean.

**Comment by mpeltonen** [comment]
It is mainly sbt itself that is doing the possibly time consuming stuff, i.e. downloading the dependencies, so there's not much you can do about it in the plugin side for the progress reporting. You could do 'set logLevel := Level.Debug' before gen-idea, but then you get lots of stuff :)

Compared to eclipse plugin, I think the defaults are different in the sense that Eclipse plugin does not download sources and javadocs by default, and sbt-idea does, and that takes more time. So better comparison would be either 'gen-idea no-classifiers no-sbt-classifiers' command or 'eclipse with-sources'.

But yes, the initial "Trying to create..." line could include information that this can take some time.

**Comment by pawelprazak** [comment]
Yes, you are absolutely right. I actually like this default behavior.

I was not aware that it's more on the sbt side. 
Than maybe, just something like this message before download would be the quick win in this situation?
`Downloading sources and documentation for dependencies.
It may take some time depending on network connection and other factors. Please be patient.
[If you don't want to wait you can skip this step: gen-idea no-classifiers no-sbt-classifiers]`

Especially for newcomers to Scala world like myself, this information is invaluable. I've spent a day trying to figure out how to make it work, because i thought it's broken and I ended up creating the project manually :P

**Comment by mpeltonen** [comment]
According to Mark's sbt 0.11.1 announcement (http://implicit.ly/simple-build-tool-0111), 0.11.1 now has finer update logging enabled by default, which should improve the situation described in this issue.

I'm planning to release 0.11.1 version of the plugin later today.

**Comment by pawelprazak** [comment]
Thanks, I look forward to it.

-- sent from Android phone
On Nov 7, 2011 8:16 AM, "Mikko Peltonen" <
reply@reply.github.com>
wrote:

**Comment by mpeltonen** [comment]
Closing this for now, as this was more of an sbt issue.
