### ISSUE TITLE
Cannot get sbt 0.11 to work with ~/.sbt/plugins/build.sbt

### ISSUE THREAD

**Issue by mslinn** [mpeltonen/sbt-idea#107]
No problem when I use sbt-idea in a project. For example, this works from the root of an sbt project:

```
$ cat project/build.sbt
resolvers += Classpaths.typesafeResolver

resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

resolvers += Classpaths.typesafeResolver

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0")

addSbtPlugin("com.typesafe.startscript" % "xsbt-start-script-plugin" % "0.3.0")

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse" % "1.4.0")
```

However, this does not:

```
$ cat ~/.sbt/plugins/build.sbt
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

resolvers += Classpaths.typesafeResolver

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0")

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse" % "1.4.0")

```

What am I missing?

**Comment by mpeltonen** [comment]
Hmm, I can't immediately suggest anything. It looks right to me, and it works for me.

Do you get the line:
[info] Loading global plugins from /home/<username>/.sbt/plugins

when launching sbt console?

**Comment by mslinn** [comment]
I have 2 Ubuntu 11.04 instances, and they emit that line. I have 2 Windows 7 Pro 64 bit instances with Cygwin and a Windows XP instance with Cygwin. The Cygwin instances to not emit that line.

**Comment by mslinn** [comment]
For Cygwin, I tried putting the .sbt directory in C:\Users<username>.sbt and that worked.
