### ISSUE TITLE
Please update the maven repo for sbt 0.11.1

### ISSUE THREAD

**Issue by weihsiu** [mpeltonen/sbt-idea#108]
sbt-0.11.1 is out.  after updating my .sbt/plugins/build.sbt to "addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.1-SNAPSHOT")", sbt errored out with this warning "[warn] ==== sbt-idea-repo: tried
[warn]   http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.1_0.11.1/0.11.1-SNAPSHOT/sbt-idea-0.11.1-SNAPSHOT.pom".  after browsing the repo, i've noticed that sbt-idea-0.11.1-SNAPSHOT.\* are in the wrong dir: they should be in sbt-idea_2.9.1_0.11.1/0.11.1-SNAPSHOT instead of sbt-idea_2.9.1_0.11.0/0.11.0.SNAPSHOT.

**Comment by mpeltonen** [comment]
Updated.
