### ISSUE TITLE
Support Scala plugin version 0.3.2039

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#11]
The Scala plugin version 0.3.2039 has been published to the update centre and it includes some changes to the Scala Facet configuration. Odd Muller made the required changes in his fork[1]. I cherry-picked on top of master in my fork[2] and tested it on a multi-module project and it works correctly.

Feel free to pull from wherever it's easier for you.

[1] http://github.com/odd/sbt-idea-plugin

[2] http://github.com/ijuma/sbt-idea-plugin/commits/master

**Comment by mpeltonen** [comment]
I cherry-picked from Odd. Should now work with 0.3.2039 (and not with older versions anymore...)
