### ISSUE TITLE
Can't resolve sbt-idea 0.11.1-SNAPSHOT when triggering 'gen-idea'

### ISSUE THREAD

**Issue by johansjoberg** [mpeltonen/sbt-idea#110]
I don't know if I am doing something wrong, but I am following the guide and when I try to generate the IntelliJ IDEA project files by triggering the gen-idea goal it can't resolve the sbt-idea plugin dependency. It however successfully resolved it during the project creation.

It seems to look in .../.ivy2/local/... which I don't have. But when looking int the ivy directory it does exist here .../.ivy2/cache/scala_2.9.1/sbt_0.11.1/com.github.mpeltonen/sbt-idea

I read that local is when you publish locally, do I need to publish the plugin locally somehow, or am I missing something?

Partial log from running 'sbt':
[info] downloading http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.1_0.11.1/0.11.1-SNAPSHOT/sbt-idea-0.11.1-SNAPSHOT.jar
 ...
[info]  [SUCCESSFUL ] com.github.mpeltonen#sbt-idea;0.11.1-SNAPSHOT!sbt-idea.jar (1737ms)

Log from running 'gen-idea':

> gen-idea
> [info] Trying to create an Idea module default-adbc71
> [info] Updating {file:/C:/dev/repo/scala/sbt-test/}default-adbc71...
> [info] Resolving org.scala-lang#scala-library;2.9.1 ...
> [info] Done updating.
> [info] Resolving org.scala-lang#scala-library;2.9.1 ...
> [info] downloading http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.9.1/scala-library-2.9.1-sources.jar ...
> [info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.9.1!scala-library.jar(src) (1698ms)
> [info] downloading http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.9.1/scala-library-2.9.1-javadoc.jar ...
> [info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.9.1!scala-library.jar(doc) (17869ms)
> [info] Excluding folder target
> [info] Created C:\dev\repo\scala\sbt-test/.idea/IdeaProject.iml
> [info] Created C:\dev\repo\scala\sbt-test.idea
> [info] Excluding folder C:\dev\repo\scala\sbt-test\target
> [info] Created C:\dev\repo\scala\sbt-test.idea_modules/default-adbc71.iml
> [info] Resolving org.scala-tools.sbt#sbt_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#main_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#actions_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#classfile_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#io_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#control_2.9.1;0.11.1 ...
> [info] Resolving org.scala-lang#scala-library;2.9.1 ...
> [info] Resolving org.scala-tools.sbt#interface;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#logging_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#process_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#classpath_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#launcher-interface_2.9.1;0.11.1 ...
> [info] Resolving org.scala-lang#scala-compiler;2.9.1 ...
> [info] Resolving org.scala-tools.sbt#incremental-compiler_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#collections_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#api_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#persist_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbinary#sbinary_2.9.0;0.4.0 ...
> [info] Resolving org.scala-tools.sbt#compile_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#ivy_2.9.1;0.11.1 ...
> [info] Resolving org.apache.ivy#ivy;2.2.0 ...
> [info] Resolving com.jcraft#jsch;0.1.31 ...
> [info] Resolving commons-httpclient#commons-httpclient;3.1 ...
> [info] Resolving commons-logging#commons-logging;1.0.4 ...
> [info] Resolving commons-codec#commons-codec;1.2 ...
> [info] Resolving org.scala-tools.sbt#completion_2.9.1;0.11.1 ...
> [info] Resolving jline#jline;0.9.94 ...
> [info] Resolving org.scala-tools.sbt#run_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#task-system_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#tasks_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#tracking_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#cache_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#testing_2.9.1;0.11.1 ...
> [info] Resolving org.scala-tools.testing#test-interface;0.5 ...
> [info] Resolving org.scala-tools.sbt#compiler-interface;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#precompiled-2_8_1;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#precompiled-2_8_0;0.11.1 ...
> [info] Resolving org.scala-tools.sbt#precompiled-2_9_0;0.11.1 ...
> [info] Resolving com.github.mpeltonen#sbt-idea;0.11.1-SNAPSHOT ...
> [warn]  module not found: com.github.mpeltonen#sbt-idea;0.11.1-SNAPSHOT
> [warn] ==== local: tried
> [warn]   C:\Users\Johan.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.9.1/sbt_0.11.1/0.11.1-SNAPSHOT/ivys/ivy.xml
> [warn] ==== Maven2 Local: tried
> [warn]   file:/C:/Users/Johan/.m2/repository/com/github/mpeltonen/sbt-idea_2.9.1_0.11.1/0.11.1-SNAPSHOT/sbt-idea-0.11.1-SNAPSHOT.pom
> [warn] ==== typesafe-ivy-releases: tried
> [warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.mpeltonen/sbt-idea/0.11.1-SNAPSHOT/ivys/ivy.xml
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea_2.9.1_0.11.1/0.11.1-SNAPSHOT/sbt-idea-0.11.1-SNAPSHOT.pom
> [warn] ==== Scala-Tools Maven2 Repository: tried
> [warn]   http://scala-tools.org/repo-releases/com/github/mpeltonen/sbt-idea_2.9.1_0.11.1/0.11.1-SNAPSHOT/sbt-idea-0.11.1-SNAPSHOT.pom
> [warn] ==== Scala-Tools Maven2 Snapshots Repository: tried
> [warn]   http://scala-tools.org/repo-snapshots/com/github/mpeltonen/sbt-idea_2.9.1_0.11.1/0.11.1-SNAPSHOT/sbt-idea-0.11.1-SNAPSHOT.pom
> [info] Resolving commons-io#commons-io;2.0.1 ...
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: com.github.mpeltonen#sbt-idea;0.11.1-SNAPSHOT: not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]
> [warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
> [warn]          com.github.mpeltonen:sbt-idea:0.11.1-SNAPSHOT (sbtVersion=0.11.1, scalaVersion=2.9.1)
> [warn]
> [error] {file:/C:/dev/repo/scala/sbt-test/}default-adbc71/*:update-sbt-classifiers: sbt.ResolveException: unresolved dependency: com.github.
> mpeltonen#sbt-idea;0.11.1-SNAPSHOT: not found
> [info] Created C:\dev\repo\scala\sbt-test.idea_modules/project.iml

**Comment by ijuma** [comment]
I ran into this too, seems like a change in sbt 0.11.1 broke sbt-idea. A workaround is `gen-idea no-sbt-classifiers`

**Comment by johansjoberg** [comment]
thanks ijuma, that seem to work for me as well.

**Comment by BowlingX** [comment]
same for me

**Comment by mpeltonen** [comment]
Thanks Ismael! I didn't run into this while I tested maybe because I didn't clean up the ivy's local-dir.

**Comment by retronym** [comment]
I'll take a look at this in the next few days.

**Comment by jrudolph** [comment]
The problem here is simple:

sbt-idea itself depends on the sbt-idea plugin of the old version, this produces the error in the end, because when running `gen-idea` there occurs some kind of conflict between the current sbt-idea version and the one sbt-idea itself depends on. The solution would be to either remove the dependency completely (you can use a global dependency anyways) or to mark it as `provided`, that seemed to work as well (I tried it only briefly, so no guarantees on that one)

**Comment by ijuma** [comment]
Thanks for looking into it. The following may answer why this worked before 0.11.1:

https://github.com/harrah/xsbt/issues/138

I like the idea of using provided.

**Comment by mpeltonen** [comment]
Thanks a lot Johannes! I'm again so tight on spare time that I don't seem to find time for debugging/fixing sbt-idea issues :(

**Comment by alexy** [comment]
Should we re-build this plugin or delete it from local ivy2 and re-download to see the effect?

**Comment by mpeltonen** [comment]
You should see this when you remove sbt-idea from local ivy repo/cache and then run gen-idea.

I think this is the same issue as #119, and is related to this sbt issue: https://github.com/harrah/xsbt/issues/304
