### ISSUE TITLE
Mark correct directory as source root for protobuf classes

### ISSUE THREAD

**Issue by nermin** [mpeltonen/sbt-idea#111]
Here is how my directory structure looks like:

target
|-scala-2.9.1
  |-src_managed
    |-main
      |-compiled_protobuf
        |-com
          |-acme
...

gen-idea marks main as a source root, which is incorrect. I then have to manually mark compiled_protobuf as the source root.

**Comment by mpeltonen** [comment]
This looks like same issue as #209, and should now be fixed in latest snapshot.
