### ISSUE TITLE
gen-idea failing to generate the project

### ISSUE THREAD

**Issue by fernandezpablo85** [mpeltonen/sbt-idea#115]
I have a simple project with only one file on src/main/scala

My build.sbt looks like this:

```
organization := "org.example.dust"

name := "dust"

version := "1.0"

scalaVersion := "2.8.1"
```

the output of `sbt gen-idea`` is:

```
[info] Loading global plugins from /Users/pfernand/.sbt/plugins
[info] Loading project definition from /Users/pfernand/Projects/dust/project
[info] Set current project to dust (in build file:/Users/pfernand/Projects/dust/)
[info] Trying to create an Idea module default-24e226
[info] Updating {file:/Users/pfernand/Projects/dust/}default-24e226...
[info] Done updating.
[info] Excluding folder target
[info] Created /Users/pfernand/Projects/dust/.idea/IdeaProject.iml
[info] Created /Users/pfernand/Projects/dust/.idea
[info] Excluding folder /Users/pfernand/Projects/dust/target
[info] Created /Users/pfernand/Projects/dust/.idea_modules/default-24e226.iml
```

Seems like everything's fine, but when I open the project on the IDE, using: File -> Open Project... and selecting the folder, I get an empty Idea screen. (I can't see the folder explorer)

I know that this issue might be short on information so please ask me whatever questions you want.

Thanks

**Comment by mpeltonen** [comment]
What is the version of Idea you're using? 11 pre/beta?

**Comment by fernandezpablo85** [comment]
Nope it's 10.5.2

**Comment by mpeltonen** [comment]
And to be sure, what are the versions of Idea Scala plugin, sbt-idea plugin and sbt?

**Comment by fernandezpablo85** [comment]
`sbt about` output

```

pfernand-2-mn:libot pfernand$ sbt about
[info] Loading global plugins from /Users/pfernand/.sbt/plugins
[info] Loading project definition from /Users/pfernand/Projects/libot/project
[info] Set current project to libot (in build file:/Users/pfernand/Projects/libot/)
[info] This is sbt 0.11.0
[info] The current project is {file:/Users/pfernand/Projects/libot/}default-3002e3
[info] The current project is built against Scala 2.8.1
[info] Available Plugins: org.sbtidea.SbtIdeaPlugin, com.typesafe.startscript.StartScriptPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.9.1
```

sbt-idea version is:

`addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0")`

And Idea Scala Plugin version is: 0.4.1183

**Comment by fernandezpablo85** [comment]
There was an issue with my Idea Installation that prevented the project view from showing no matter what.

I've uninstalled and reinstalled the latest version (11 at the time I'm writing this) and pressed `⌘1` that did the trick.

Sorry for wasting your time, and many thanks for sbt-idea
