### ISSUE TITLE
Compiler output directories contain wrong Scala version

### ISSUE THREAD

**Issue by hseeberger** [mpeltonen/sbt-idea#12]
I just used the processor to create IDEA project files for a multi module SBT project that is built against 2.8.0 only. But all the compiler output directories contain _scala_2.8.0.RC3_ in the path, e.g. _/Users/hseeberger/projects/petag/petag-db/target/scala_2.8.0.RC3/classes_.

**Comment by mpeltonen** [comment]
I can't reproduce this. Because plugin gets the path from SBT (mainCompilePath), having RC3 in output path should, in theory, be possible only if you have "build.scala.versions=2.8.0.RC3" in your project/build.properties.

**Comment by hseeberger** [comment]
I can't reproduce it my own. Yesterday was a bad day ;-) Sorry for the spam!

**Comment by mpeltonen** [comment]
No problem. I'm familiar with those days :)
