### ISSUE TITLE
Set deprecation and unchecked scalac options

### ISSUE THREAD

**Issue by mdekstrand** [mpeltonen/sbt-idea#120]
When `scalacOptions` contains `-deprecation` and/or `-unchecked`, the corresponding options should be set in the generated Scala facet configuration.

**Comment by ziggystar** [comment]
Also in my setup, the contents of `scalacOptions` is not added to the project. So I have to set things like dependent method types each time anew.

**Comment by mslinn** [comment]
+1

**Comment by jozic** [comment]
this issue can be closed now
