### ISSUE TITLE
Publish to scala-tools.org

### ISSUE THREAD

**Issue by dln** [mpeltonen/sbt-idea#123]
It seems sbt-idea is so commonly used, it'd make sense to publish it to the scala-tools repo.
This would make it usable directly from sbt without having to change/add resolvers manually.

**Comment by mpeltonen** [comment]
Yes, you're right and I've been thinking about it. I will contact scala-tools admin.

**Comment by mpeltonen** [comment]
Interestingly, the response was: "Sadly, we've decided to wind down scala-tools.org and are not accepting any new submissions.  Sorry."

So I think this case is closed :(

**Comment by dln** [comment]
Yeah I got the same message, about the day before dpp decided to close it I suppose...
I got an account at sonatype and published some stuff there, no problems at all so far.

I guess either publish there, or for sbt-idea it might make sense to use the new sbt community repo: http://www.scala-sbt.org/community-plugins.html

Cheers,
/d
