### ISSUE TITLE
Working with multiple projects

### ISSUE THREAD

**Issue by riedelcastro** [mpeltonen/sbt-idea#125]
I have two sbt projects A and B, and A depends on B. However, they are not part of a multi-project, and should not be. I would like to still jointly work on both in idea, without going through a publish-local, gen-idea cycle after every change to B. What is the recommended way to do this? 

Many thanks!
Sebastian

**Comment by mpeltonen** [comment]
With the latest snapshot (0.11.1-SNAPSHOT at the time of writing) you should be able to do something like this:

Project A:

``` scala
import sbt._

object A extends Build {
  lazy val A = Project("A", file(".")) aggregate(B) dependsOn(B)
  lazy val B = RootProject(file("../B"))
}
```

Project B:

``` scala
import sbt._

object B extends Build {
  lazy val B = Project("B", file("."))
}
```

Now (you need also sbt-idea plugin config for the projects of course) running gen-idea on A should create Idea module also for B and make A to depend on it.

**Comment by riedelcastro** [comment]
Works perfectly, thanks!
