### ISSUE TITLE
Looks like the plugin does not support the latest version 0.3.2039 of Scala IDEA plugin

### ISSUE THREAD

**Issue by hseeberger** [mpeltonen/sbt-idea#13]

**Comment by ijuma** [comment]
It should, see http://github.com/mpeltonen/sbt-idea-plugin/issues/closed#issue/11 .

**Comment by mpeltonen** [comment]
Please be more specific. I have 0.3.2039 and my multiproject seems to work in Idea just fine after "sbt idea" and import.

Have you tried cleaning the ivy cache, to be sure you have the latest version (for example rm -rf ~/.ivy2/cache/com.github.mpeltonen)?

**Comment by hseeberger** [comment]
I used the processor. Do I have to clean the Ivy Cache then? Maybe this is related to #12.

**Comment by mpeltonen** [comment]
Yes, the processor is also retrieved into ~/.ivy2/cache/com.github.mpeltonen/sbt-idea-processor_2.7.7/ and it may be that ivy does not check if snapshot is updated, I don't know?

Haven't had time to investigate #12 yet.

**Comment by hseeberger** [comment]
I tried with another project and it worked. Probably my mistake.
Sorry for the spam!
