### ISSUE TITLE
[error] impossible to get artifacts when data has not been loaded. 

### ISSUE THREAD

**Issue by analytically** [mpeltonen/sbt-idea#130]
Hi,

After adding Esper 4.5 to my project dependencies, your plugin fails. Here the logging details:

[info] Trying to create an Idea module Hydrodesk Analytics
[error] impossible to get artifacts when data has not been loaded. IvyNode = org.antlr#stringtemplate;3.2.1
[error] {file:/home/mathias/Development/hydrodesk/analytics/}Hydrodesk Analytics/*:update-classifiers: java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.antlr#stringtemplate;3.2.1
[info] Excluding folder target
....

My import:

"com.espertech" % "esper" % "4.5.0" excludeAll(
      ExclusionRule(organization = "log4j"),
      ExclusionRule(organization = "commons-logging")
    )

Same happens with or without the excludeAll stuff.

**Comment by mpeltonen** [comment]
Seems to be more Ivy related than the plugin or sbt related problem. Also the problem happens in sbt-level, try running for example the 'update-classifiers' sbt task. 

Declaring the stringtemplate explicitly as a dependency seems to be a workaround.

But anyway, seems like nothing can be done in plugin code to fix this.
