### ISSUE TITLE
Add src/it to test resources

### ISSUE THREAD

**Issue by fmpwizard** [mpeltonen/sbt-idea#131]
The plugin adds src/test/scala to tests and src/main/scala as source code.
When developing web applications, you can also have:

src/it/resources and src/it/scala where you can have Integration tests (selenium for example. (this it folder was taken from the sbt wiki page)

Now I manually added it to my IntelliJ config, but it would be nice if  the plugin could add it, or is there a way to customize the plugin without having to modify the code of the plugin?

The screen to manually do this is Project structure -> Modules -> <select your project there> -> sources tab -> and on the right hand side, select the it/scala folder and then press "Test resources"

Thanks

**Comment by mpeltonen** [comment]
Which version of the plugin you're using? Latest 1.0 version supports integrationtest directories (see https://github.com/mpeltonen/sbt-idea/pull/121). 

You can find config example in the scripted tests: https://github.com/mpeltonen/sbt-idea/blob/master/src/sbt-test/sbt-idea/with-integration-tests/project/Build.scala

**Comment by fmpwizard** [comment]
Sorry, it works perfectly! I forgot to reload intellij after running gen-idea
