### ISSUE TITLE
Mistake in Readme.md

### ISSUE THREAD

**Issue by amorfis** [mpeltonen/sbt-idea#133]
In Readme.md, "Installation" section, there is:

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.0.0")

At least for SBT 0.11.0, it should be:

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0")

**Comment by mpeltonen** [comment]
Also, the requirements section says "sbt 0.11.2" :)

So the latest 1.0 only works with latest sbt. With 0.11.0 sbt you still can use 0.11.0 version of the plugin. Whether older versions of sbt should be documented in readme is debatable... :)

**Comment by amorfis** [comment]
Well, it works well with 0.11.0 too, all is needed is just change of
this number. I think it could be documented too.

## Anyway, thanks for this nice, useful plugin.

Paweł Stawicki
http://pawelstawicki.blogspot.com
http://szczecin.jug.pl

On Thu, Feb 9, 2012 at 06:13, Mikko Peltonen
reply@reply.github.com
wrote:
