### ISSUE TITLE
Wrong "compile output path" for "project" module

### ISSUE THREAD

**Issue by OlegYch** [mpeltonen/sbt-idea#134]
Should be "file://$MODULE_DIR$/../project/target/scala-2.9.1/sbt-0.11.2/classes" not "file://D:\Distrib\Coding\Java\scala\Play20\framework\project\target\scala_2.9.1".

Useful when you want to start "Scala Console" for "project" module.

**Comment by mpeltonen** [comment]
Should be now fixed in master (currently for sbt 0.12.x only).
