### ISSUE TITLE
Totally breaks on mounted devices due to absolute paths

### ISSUE THREAD

**Issue by gerdriesselmann** [mpeltonen/sbt-idea#135]
What it does:

All the gen-idea commands generates is a project named "default-d8b7ce" which contains the managed libraries but nothing else.

Expected:

1.) The project is named similar to the sbt name 

2.) In Idea I'm able to browse the .scala files and packages beneath /src/main/scala and /test/main/scala

Reason:

I figured out that the absolute path to the project was set as Idea ContentRoot. However, since I'm running Idea on another computer (the code actually is on a test server), and the directory is mounted there, the content root does not match. This was no problem with the 0.7 version.

When comparing the files generated by the plugin and the ones Idea itself writes, I noticed that Idea simply uses $MODULE_DIR$ and paths relative to it.

$MODULE_DIR$ identifies the location of the .iml file, which happen to be .idea. src/main/scala then is defined as $MODULE_DIR$/../src/main/scala.

The plugin on the other hand uses the absolute paths everywhere, which breaks.

**Comment by gerdriesselmann** [comment]
Update:

With current 1.1.0-SNAPSHOT on sbt 0.12.0-RC1 most absolute paths in project .iml are gone, except of one, which is generated on line 54 of IdeaModuleDescriptor.scala:

```
<content url={"file://" + relativePath(project.baseDir) }>
```

There are still a couple of it in the project-build.iml, however.

I also noticed that I can avoid the name being default-XXX by adding ProjectBuild.scala to /project with a simple project definition:

```
import sbt._
import Keys._

object ProjectBuild extends Build {
    lazy val root = Project(id = "project-name", base = file("."))
}
```

This will generate a project-name.iml and project-name-build.iml.
Maybe this should be put in the docs somewhere.

**Comment by mpeltonen** [comment]
This should be now fixed. Open a new issue if not!
