### ISSUE TITLE
non-default project naming

### ISSUE THREAD

**Issue by alexy** [mpeltonen/sbt-idea#136]
What is a minimal short or full SBT project configuration which will produce a non-default project and module name with gen-idea?

**Comment by aryairani** [comment]
As far as I know, you have to use a full SBT project configuration:

``` scala
import sbt._
object Whatever extends Build {
  lazy val root = Project("whatever", file("."))
}
```

which wouldn't be so bad if you didn't also have to make a directory for it.

Mikko, would using the project name for the idea module name, rather than the project id, be an option?

**Comment by alexy** [comment]
Please just use the project name, making folks use a full build
definition is redundant for the simple case.

A+

On Sat, Mar 31, 2012 at 6:41 PM, refried
reply@reply.github.com
wrote:

**Comment by mpeltonen** [comment]
Name would be better, but if my memory serves me right, there was some problem in using project name with regards to linking with subprojects in multiproject setup. But I'm not sure. I need to check this again.

**Comment by aryairani** [comment]
If the issue is about potential name conflicts: Mark had indicated that the
project names in xsbt are necessarily unique within a given build, and in
different namespaces across dependent builds.  Not understanding the
internals myself, I don't know whether this helps any though.

On Wed, Apr 4, 2012 at 1:25 PM, Mikko Peltonen <
reply@reply.github.com

**Comment by alexy** [comment]
Can we still get a default name?  At least have an option of using the existing name in build.sbt for project name -- otherwise I have to mechanically create the Build.scala as above, which hopefully can be automated?

**Comment by mpeltonen** [comment]
Latest snapshot now uses project name as Idea module name if the project is single-module project. I guess it should be perfectly safe in this case, and fixes most of the cases?
