### ISSUE TITLE
How to use with sbt-0.12 ?

### ISSUE THREAD

**Issue by andreak** [mpeltonen/sbt-idea#138]
Using sbt-0.12 I get:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.mpeltonen:sbt-idea:1.0.0 (sbtVersion=0.12, scalaVersion=2.9.1)

**Comment by mpeltonen** [comment]
Any version of 0.12 is not found in any public repository yet (as far as I know), so you have to build also sbt-idea locally with 0.12. 

Changing the sbt.version in project/build.properties to a version you have built locally should work (haven't tested though). I.e. do './sbt publish-local' after changing sbt version.

**Comment by andreak** [comment]
Thanks, how do I build sbt-idea with 0.12?

**Comment by mpeltonen** [comment]
Like I tried to describe in the second paragraph of my previous answer :-)

**Comment by mpeltonen** [comment]
I.e. clone the sbt-idea repo first. Then change the project/build.properties file, then './sbt publish-local'. 

That might or might not work out-of-the-box...

**Comment by andreak** [comment]
Am I really _that_ blind?? Sorry:-)

**Comment by andreak** [comment]
I've downloaded sbt-0.12.0-M1 from https://github.com/harrah/xsbt/zipball/v0.12.0-M1 but have no idea how to build and install it locally so that sbt-idea will find it. Any hints?

**Comment by mpeltonen** [comment]
Probably the easiest way is to follow the 'Build from source' instructions in https://github.com/harrah/xsbt/blob/0.12/README.md

**Comment by andreak** [comment]
I've built 0.12.0-M1 from source now using "sbt build-all" but I still get this error:

```
            module not found: org.scala-tools.sbt#sbt_2.9.1;0.12.0-M1

    ==== local: tried

      /home/andreak/.ivy2/local/org.scala-tools.sbt/sbt_2.9.1/0.12.0-M1/ivys/ivy.xml
```

And the installed version is here:
/home/andreak/.ivy2/local/org.scala-sbt/sbt/0.12.0-M1/ivys/ivy.xml

Any hints.

**Comment by harrah** [comment]
0.12.0-M1 was release about a month ago (announcement [here](https://groups.google.com/group/simple-build-tool/browse_thread/thread/9d9c9c2b60e6d1f6/d4c6ac6f9ce6619f)), so there is no need to build it from source.

In any case, you need to use the 0.12.0-M1 launcher with it and it looks like you are using the 0.11 launcher.

**Comment by harrah** [comment]
(Correction: not a month ago, just a couple of weeks ago)

**Comment by mpeltonen** [comment]
Ah, the reason I didn't find it from repo was the package change. Thanks!

**Comment by andreak** [comment]
I'm trying to build sbt-idea with buidl.properties like this:

sbt.version=0.12.0-M1

using "xsbt" which is:
$ cat ~/bin/xsbt
#!/bin/bash
java -XX:MaxPermSize=512m -Xmx2g -jar $HOME/dev/sbt-0.12.0-M1/sbt-launch-0.12.0-M1.jar "$@"

But still:
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.mpeltonen:sbt-idea:1.0.0 (sbtVersion=0.12, scalaVersion=2.9.1)

Seems it's trying to resolv sbtVersion=0.12 and not 0.12.0-M1, any hints?

**Comment by mpeltonen** [comment]
Do you have sbt-idea plugin defined as global plugin in ~/.sbt/? You need to remove that, because otherwise sbt tries to find something that does not exist.

**Comment by andreak** [comment]
Hm, in my .sbt/plugins/build.sbt I had:

resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.0.0")

Commenting out I get:
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-tools.sbt#scripted-plugin_2.9.1;0.12.0-M1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

Anyone has a recipe for making a sbt-idea version which works with 0.12.0-M1 ?

**Comment by mpeltonen** [comment]
Mark: trying to compile with 0.12.0-M1, scripted plugin is again a bit of a problem. Sbt tries to find http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-sbt_2.9.1/0.12.0-M1/ivys/ivy.xml (with scala version) and that does not exist.

Sbt seems to put the scala version in there in any case, even "libraryDependencies += "org.scala-sbt" % "scripted-plugin" % "0.12.0-M1"" does not work and it tries to resolve with _2.9.1 included.

How should I declare the scripted plugin, or should it be deployed also with _2.9.1?

**Comment by harrah** [comment]
It works for me with that line.  To be precise, I changed `project/build.properties` to `sbtVersion=0.12.0-M1` and the dependency in `project/plugins.sbt` to:

``` scala
libraryDependencies <+= sbtVersion("org.scala-sbt" % "scripted-plugin" % _)
```

(I know you acknowledged both of these changes, but make sure to both use one % as well as use the new group ID.)

**Comment by andreak** [comment]
After modifying project/plugins.sbt it found the deps, but fails with:

<pre>
$ cat sbt
#!/bin/bash
cd $(dirname $0)
java -Xmx256m -jar sbt-launch*.jar $*

[andreak@andreak-Precision-M6600] ~/dev/sbt-idea [master] 
$ ls
LICENSE  notes  project  README.md  sbt  sbt-launch-0.12.0-M1.jar  set_tested_version.sh  src
[andreak@andreak-Precision-M6600] ~/dev/sbt-idea [master] 
$ ./sbt 
[info] Loading global plugins from /home/andreak/.sbt/plugins
[info] Loading project definition from /home/andreak/dev/sbt-idea/project
[info] Compiling 1 Scala source to /home/andreak/dev/sbt-idea/project/target/scala-2.9.1/sbt-0.12/classes...
[error] /home/andreak/dev/sbt-idea/project/Build.scala:2: not found: object Keys
[error] import Keys._
[error]        ^
[error] one error found
[error] {file:/home/andreak/dev/sbt-idea/project/}default-3944f5/compile:compile: Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
</pre>


Any hints?

And again, thanks for spending time on this. My goal is to be able to use this plugin with the Lift-project so it can generate the IDEA-project for me.

**Comment by mpeltonen** [comment]
Hmm, for me it compiles project definition fine, but running 'compile' does not work. Here's my diff to master:

``` diff
diff --git a/project/build.properties b/project/build.properties
index f4ff7a5..84c152a 100644
--- a/project/build.properties
+++ b/project/build.properties
@@ -1 +1 @@
-sbt.version=0.11.2
+sbt.version=0.12.0-M1
diff --git a/project/plugins.sbt b/project/plugins.sbt
index eb8e3b0..96dcb17 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -3,5 +3,4 @@ resolvers ++= Seq(
   "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"
 )

-libraryDependencies <+= sbtVersion("org.scala-tools.sbt" %% "scripted-plugin" % _)
-
+libraryDependencies <+= sbtVersion("org.scala-sbt" % "scripted-plugin" % _)
```

Console starts fine, but 'compile' or 'publish-local' produces:

``` code
[info] Resolving org.scala-sbt#precompiled-2_9_0;0.12.0-M1 ...
[info] Resolving org.scala-sbt#scripted-sbt_2.9.1;0.12.0-M1 ...
[warn]  module not found: org.scala-sbt#scripted-sbt_2.9.1;0.12.0-M1
```

**Comment by mpeltonen** [comment]
And of course I changed the launcher jar too.

**Comment by andreak** [comment]
Strange, that's exactly what my diff looks like:

``` diff
$ git diff master
diff --git a/project/build.properties b/project/build.properties
index f4ff7a5..84c152a 100644
--- a/project/build.properties
+++ b/project/build.properties
@@ -1 +1 @@
-sbt.version=0.11.2
+sbt.version=0.12.0-M1
diff --git a/project/plugins.sbt b/project/plugins.sbt
index eb8e3b0..96dcb17 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -3,5 +3,4 @@ resolvers ++= Seq(
   "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"
 )

-libraryDependencies <+= sbtVersion("org.scala-tools.sbt" %% "scripted-plugin" % _)
-
+libraryDependencies <+= sbtVersion("org.scala-sbt" % "scripted-plugin" % _)
diff --git a/sbt-launch-0.11.2.jar b/sbt-launch-0.11.2.jar
deleted file mode 100644
index 84fd9b7..0000000
Binary files a/sbt-launch-0.11.2.jar and /dev/null differ
```

Did you clean before building?

**Comment by andreak** [comment]
Hm, how do I paste diffs so that markdown (or whatever it is) won't eat lines?

**Comment by mpeltonen** [comment]
I've tried these cleanups before building:

``` code
rm -rf target
rm -rf project/project
rm -rf project/target
rm -rf ~/.ivy2
```

**Comment by mpeltonen** [comment]
For the code blocks, see 'Syntax highlighting' in http://github.github.com/github-flavored-markdown/

You can use 'code', 'diff', 'scala' etc in place of 'ruby'.

**Comment by andreak** [comment]
This helped getting the console up:

``` code
rm -rf ~/.ivy2
```

Now I'm getting the same as you:

``` code
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#scripted-sbt_2.9.1;0.12.0-M1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/home/andreak/dev/sbt-idea/}sbt-idea/*:update: sbt.ResolveException: unresolved dependency: org.scala-sbt#scripted-sbt_2.9.1;0.12.0-M1: not found
[error] Total time: 5 s, completed Mar 7, 2012 9:03:13 AM
```

**Comment by mpeltonen** [comment]
I just pushed 'sbt-0.12' branch which should compile (removed scripted plugin for now).

**Comment by andreak** [comment]
Great, it builds fine now, thanks!

How do I use this version in my project? I've tried having the following in ~/.sbt/plugins/build.sbt:

<pre>
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.1.0-SNAPSHOT")
</pre>


But that leads to:

<pre>
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;1.1.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.mpeltonen:sbt-idea:1.1.0-SNAPSHOT (sbtVersion=0.12, scalaVersion=2.9.1)
</pre>


I don't know why its trying sbtVersion=0.12 when my project/build.properties has:

<pre>
sbt.version=0.12.0-M1
</pre>


Any ideas?

**Comment by mpeltonen** [comment]
No idea why it uses 0.12 there. Doing this seems to be a workaround:

``` code
mv ~/.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.9.1/sbt_0.12.0-M1 ~/.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.9.1/sbt_0.12
sed -i .bak 's/0.12.0-M1/0.12/g' ~/.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.9.1/sbt_0.12/1.1.0-SNAPSHOT/ivys/ivy.xml
```

**Comment by andreak** [comment]
Thanks, that works.

**Comment by mpeltonen** [comment]
Here's a working way to declare plugins built from milestone versions:

``` code
libraryDependencies <+= sbtVersion(Defaults.sbtPluginExtra("com.github.mpeltonen" % "sbt-idea" % "1.1.0-SNAPSHOT", _, "2.9.1"))
```

**Comment by gthiruva** [comment]
Should this be resolvable from 

```
libraryDependencies <+= sbtVersion(Defaults.sbtPluginExtra("com.github.mpeltonen" % "sbt-idea" % "1.1.0-SNAPSHOT", _, "2.9.1"))
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"
```

When I do that, it tries to construct this URL:

```
http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.1_0.12.0-M2/1.1.0-SNAPSHOT/sbt-idea-1.1.0-SNAPSHOT.pom
```

But it fails. When I look in `http://mpeltonen.github.com/maven/com/github/mpeltonen/` I only see 1.1.0-SNAPSHOT builds for sbt 0.11.x - not 0.12.

**Comment by mpeltonen** [comment]
The builds against 0.12 milestones are not in the repo. Currently you need to do publish-local of sbt-0.12 branch first.

**Comment by gthiruva** [comment]
Yeah, that's what I ended up doing. It built pretty cleanly even with 2.9.1-1. Got a little confused by the discussion about setting the resolvers. Thanks!

**Comment by mpeltonen** [comment]
Just pushed a snapshot binary for sbt-0.12.0-Beta2 into repository.

Can be used with this declaration in plugins.sbt:

``` code
libraryDependencies <+= sbtVersion(Defaults.sbtPluginExtra("com.github.mpeltonen" % "sbt-idea" % "1.1.0-SNAPSHOT", _, "2.9.2"))
```
