### ISSUE TITLE
add rt.jar to idea's classpath

### ISSUE THREAD

**Issue by Intellicode** [mpeltonen/sbt-idea#14]
I'm trying to use an HttpURLConnection, but idea said it cannot recognize the symbol java when importing java.net.HttpURLConnection

**Comment by Intellicode** [comment]
Turns out, I need to add a java sdk to idea which adds rt.jar among others to the classpath

**Comment by mpeltonen** [comment]
Yes. JDK and its classpath is configured in Module Settings -> SDK's.
