### ISSUE TITLE
add sbt source files to idea

### ISSUE THREAD

**Issue by bblfish** [mpeltonen/sbt-idea#140]
Every so often I need to edit the build.scala of some project - looking at the source for sbt
to understand  the build file and to see what new things I could use is very useful there. 
But the source code does not end up being linked to in the idea files you generate. 

In order to get the source jars I then have to build xsbt from git, generate the source jars, and put 
it in a global library. But then whenever I rebuild the sbt file with sbt-idea it overwrites that change. 
Also as I move around from  project to project I find that there may be different versions of xsbt
used by each project so that this end up being very tedious. Furthermore it often happens that 
I go months without doing this, and each time I come back to the problem I have to rediscover all
the issues above once more.

Is there a way that like with all other useful jars one could find the source easily for xsbt?

**Comment by OlegYch** [comment]
i find this very useful too, but it seems to be working for me ootb
do you use gen-idea with-classifiers with-sbt-classifiers ?

**Comment by bblfish** [comment]
Ah I did not notice those. 

I just tried it with 

``` scala
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

addSbtPlugin("com.github.mpeltonen" %% "sbt-idea" % "1.1.0-SNAPSHOT")
```

in that version one has to write

```
> gen-idea sbt-classifiers
```

But it does not work. Once it regenerates my idea project, and after IntelliJ restarts, if I go to the `Build.scala` file and cmd-b on say sbt.Build I end up with a decompiled source of that class not the source. 

Coult it be that it does not work witht the latest version?

Btw, `help gen-idea` does not return anything. A bit of text on the options there and their meanings would be useful. :-)

**Comment by dimgel** [comment]
`gen-idea sbt-classifiers` helped me too, thanks a lot! Although it took some time to find this ticket and this option. I suppose this option should be default, same as for other classifiers (and no-sbt-classifiers same as no-classifiers, or no separate option for sbt classifiers at all).
