### ISSUE TITLE
find locally-published jars

### ISSUE THREAD

**Issue by bblfish** [mpeltonen/sbt-idea#143]
Sometimes I am working with bleeding edge code, which is not published. So I compile it and then publish it locally. It does not seem that idea picks the locally published one up. It still seems to search for the remote ones.

Come to think of it I wonder if there would be a way to make sure that the latest locally published version is always used. A symbolic link to the ivy or maven file perhaps?

**Comment by bblfish** [comment]
I tried adding a `local` resolver to my plugins, but that did not seem to help

```
$ cat ~/.sbt/plugins/build.sbt 
resolvers += "local" at "file:///Users/hjs/.ivy2/local/"

resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

//addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.0.0")

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.1.0-SNAPSHOT")
```

**Comment by mpeltonen** [comment]
Local ivy repo is always included by default. You don't have to do anything.

For example, if i change the sbt-idea plugin's version in some project to 1.1.1-SNAPSHOT, which does not exist anywhere, the update tells among others:

``` code
...
[warn] ==== local: tried
[warn]   /home/mpe/.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.9.1/sbt_0.12/1.1.1-SNAPSHOT/ivys/ivy.xml
...
```

Make sure that you publish-local the plugin for the same version of scala/sbt as where you're using it?

**Comment by bblfish** [comment]
Mhh. ok. I'll check that I am using the same scala/sbt version. That could have been the issue....
