### ISSUE TITLE
Test JAR dependency not included in "external libraries" in IntelliJ project

### ISSUE THREAD

**Issue by taylorleese** [mpeltonen/sbt-idea#145]
I have a dependency defined like below:

"com.foo" %% "foo" % 1.0.0 % "test" classifier "test" withSources() changing()

This is to pull in the test JAR artifact and it works fine from the command line with sbt, but when running gen-idea there is no external library reference for the test JAR.

**Comment by mpeltonen** [comment]
Yes, only the artifact without classifier was considered as the 'classes' jar. 

I changed the logic so that also any classifier that is not javadoc or source classifier is considered to be classes. Try the latest 1.1.0-SNAPSHOT, if it works for you.

**Comment by taylorleese** [comment]
Updated build.properties to: 

``` scala
sbt.version=0.11.2
```

Updated plugins.sbt to: 

``` scala
addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.1.0-SNAPSHOT")
```

Unfortunately, I'm still having the same problem. Here are how the dependencies are defined in my build.sbt:

``` scala
libraryDependencies ++= {
  val curatorVersion = "1.0.6"
  val commonVersion = "0.2.0-SNAPSHOT"
  Seq(
    "com.myco" %% "myco-common" % commonVersion withSources() changing(),
    "com.netflix.curator" % "curator-client" % curatorVersion withSources(),
    "com.netflix.curator" % "curator-framework" % curatorVersion withSources(),
    "com.netflix.curator" % "curator-recipes" % curatorVersion withSources(),
    "org.specs2" %% "specs2" % "1.7.1" % "test" withSources(),
    "org.mockito" % "mockito-all" % "1.9.0" % "test" withSources(),
    "com.myco" %% "myco-common" % commonVersion % "test" classifier "test" withSources() changing()
  )
}
```

Note, the myco-common dependency is something internal in our Nexus repository and I am pulling in the standard (non-classifier) dependency as a compile time dependency and the classifier "test" dependency as a test dependency. Please let me know if you need anymore information.

**Comment by mpeltonen** [comment]
Hmm, the reason might be that you have both, the non-classifier and the 'test' classifier versions, as dependencies. My test didn't take that (probably more common) scenario into account. 

I'll look into this more when I find some time.

**Comment by mpeltonen** [comment]
The reason was what I thought above, but fixing it is not as easy as I thought. But working on it, bit by bit (if I only had more time...) :-)

**Comment by mpeltonen** [comment]
And I think #104 is related to this.

**Comment by taylorleese** [comment]
Great, sounds like it's fixable in due time at least. :-)

**Comment by mpeltonen** [comment]
I just pushed new 1.1.0-SNAPSHOT with a fix which works for this situation at least in my test case. Could you test if this makes any difference in your setup?

**Comment by taylorleese** [comment]
Yes, it worked but I did notice that the source and javadocs for the test JAR were not included correctly. They are referencing the non-test classifier sources and javadocs.

**Comment by mpeltonen** [comment]
Ok thanks! I guessed there might be a problem with sources/javadocs, but I couldn't quickly find deployed examples of sources and javadocs for other classifiers.

So are the source/javadoc jars for other classifiers named like 

``` code
"..<version>-<classifier>-sources.jar" etc.?
```

**Comment by taylorleese** [comment]
Yes, if test is the classifier...

*-test-javadoc.jar
*-test-sources.jar

**Comment by mpeltonen** [comment]
Do you happen to know any artifacts with sources/javadocs also for 'classified' jars from public repositories, for test case?

**Comment by taylorleese** [comment]
http://search.maven.org/#search%7Cga%7C1%7Ctest-sources

**Comment by mpeltonen** [comment]
Thanks! Now I found some artifacts (tried that search before, but didn't get to the right ones).

**Comment by mpeltonen** [comment]
The reason they get included is that Ivy (or sbt) downloads them also for classified artifacts, i.e. with this declaration:

``` code
"com.googlecode.kiama" % "kiama_2.9.1" % "1.2.0" % "test" classifier "test" withSources() intransitive()
```

I get this from sbt's updatereport:

``` code
[info]  test:
[info]      org.scala-lang:scala-library:2.9.1: (Artifact(scala-library,jar,jar,None,List(),None,Map()),/var/folders/c6/sgwzkyn93594s0594gr7pv9m0000gn/T/sbt_2c8ddb7c/dependency-with-classifier/global/boot/scala-2.9.1/lib/scala-library.jar)
[info]      com.googlecode.kiama:kiama_2.9.1:1.2.0: 
[info]          (Artifact(kiama_2.9.1,jar,jar,Some(test),List(),None,Map()),/Users/mpe/.ivy2/cache/com.googlecode.kiama/kiama_2.9.1/jars/kiama_2.9.1-1.2.0-test.jar)
[info]          (Artifact(kiama_2.9.1,src,jar,Some(sources),List(),None,Map()),/Users/mpe/.ivy2/cache/com.googlecode.kiama/kiama_2.9.1/srcs/kiama_2.9.1-1.2.0-sources.jar)
```

I.e. I get the -sources artifact, not -test-sources artifact. Same with the 'update-classifiers' sbt task.

This way I get them downloaded, but they end up in /jars/ directory instead of /src/:

``` code
"com.googlecode.kiama" % "kiama_2.9.1" % "1.2.0" % "test" classifier "test" classifier "test-sources" intransitive()
```

So I don't currently know how you'd declare and download "test-sources.jar" as source jar, or whether there's some problem with this in Ivy or sbt. 

But I'll try to filter out the 'wrong' source/javadoc jar from the update-classifiers output, so that the non-classifier sources/javadocs wouldn't get referenced within test classifier idea library.

**Comment by mpeltonen** [comment]
Hmm, I think I'll leave it this way until I understand more about the sources/javadocs download with regards to classified artifacts. 

I think it may even be correct in some cases that module-level -sources.jar includes sources of multiple classified artifacts, no? 

Or can I always assume that foo-X.X.X-sources.jar does not include sources of foo-X.X.X-bar.jar but it may have corresponding foo-X.X.X-bar-sources.jar? How can I tell it to sbt/Ivy?

**Comment by taylorleese** [comment]
Honestly, my inclination is to believe this is a an Ivy bug. Side note, Maven doesn't work this way and downloads sources/javadocs correctly for classifiers, but then again Maven does lots of things correctly that Ivy doesn't do. I don't understand why it wouldn't always download the sources and javadocs for the specified classifier. It doesn't make sense for it to work otherwise in my mind.

**Comment by taylorleese** [comment]
Regardless, that's for tracking down the most important part of the issue. Much appreciated.
