### ISSUE TITLE
Generating project file for playframework 2.0 with configured sources

### ISSUE THREAD

**Issue by omj** [mpeltonen/sbt-idea#148]
Using http://www.playframework.org/documentation/2.0/NewApplication instructions I create 2 following files 
**project/plugins.sbt**

```
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

addSbtPlugin("play" % "sbt-plugin" % "2.0")

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.0.0")
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.0.0")
```

**project/Build.scala:**

```
import sbt._
import Keys._
import PlayProject._
object ApplicationBuild extends Build {
  val appName         = "My first application"
  val appVersion      = "1.0"
  val appDependencies = Nil
  val main = PlayProject(
    appName, appVersion, appDependencies, mainLang = SCALA
  ) 
}
```

and run **sbt idea**. After execution of this command I have an iml file with empty sources tags, However **sbt eclipse with-source=true** generates .classpath file with sources.

**Comment by ijuma** [comment]
You are using the command from Play. To use this one, run gen-idea.

**Comment by omj** [comment]
It works, thanks! Used eclise for learning Play, it was a nightmare :)
