### ISSUE TITLE
Language Level defaults to 5.0

### ISSUE THREAD

**Issue by svefors** [mpeltonen/sbt-idea#15]
Now, I am not really an expert in IDEA, but the section that controls the Language Level of the project is in the *.ipr file.

component name="ProjectRootManager" version="2" languageLevel="JDK_1_5" assert-keyword="true" jdk-15="true" project-jdk-name="1.6" project-jdk-type="JavaSDK" 
    output url="file://$PROJECT_DIR$/out" 
  component

When you run sbt the 'idea' action it will by default set the languageLevel="JDK_1_5" in the IdeaProjectDescriptor class. I could be mistaken, but I think the default for SBT is to consider the java sources as 1.6 language level. If so, it would make sense that the default Language Level was JDK_1_6.

Or maybe there could be a setting/property to specify? As it is now, I have to update and reload the project from IDEA everytime I run the  sbt idea action.

**Comment by mpeltonen** [comment]
I changed 'languageLevel' configurable, defaulting to JDK_1_6.
