### ISSUE TITLE
assembly classifier

### ISSUE THREAD

**Issue by tmcgrath** [mpeltonen/sbt-idea#151]
Hi,
Using 0.11.1-SNAPSHOT and producing .idea/libraries/common.xml:

Using ... to anonymize--

```
<component name="libraryTable">
  <library name="...common_2.9.1_0.5.0.3">
    <CLASSES />
    <JAVADOC>
      <root url="jar://$USER_HOME$/.ivy2/cache/.../docs/...common-javadoc.jar!/" />
    </JAVADOC>
    <SOURCES>
      <root url="jar://$USER_HOME$/.ivy2/cache/.../srcs/...common-sources.jar!/" />
    </SOURCES>
  </library>
</component>
```

Problem is CLASSES node is not including the .jar which is in:
/.ivy2/cache/.../jars/common_2.9.1-0.5.0.3-assembly.jar

In essence, build.sbt looks like:
libraryDependencies ++= Seq(
   "com.blah" %% "...common" % "0.5.0.3" classifier "assembly" intransitive() changing(),
)

Any ideas on how to resolve?

**Comment by mpeltonen** [comment]
Is the version 0.11.1-SNAPSHOT correct? Just making sure as latest version of the plugin is 1.1.0-SNAPSHOT and it contains improvements for classified artifacts.

**Comment by tmcgrath** [comment]
It is, but no worries.  We changed our deploy and don't have need for classifier anymore
