### ISSUE TITLE
Sources not found if outside the classpath

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#16]
If one has Java dependencies with sources, it's important to override the outputPath so that sources don't go in the classpath (otherwise javac tries to compile them), see the following comment for the pattern recommended by Mark Harrah::

http://code.google.com/p/simple-build-tool/issues/detail?id=44#c8

This breaks this plugin as it searches the classpath for source jars.

**Comment by ijuma** [comment]
Not sure if this is the best way to fix it, but I pushed a potential fix to my fork:

http://github.com/ijuma/sbt-idea-plugin/commit/7132e6b5f92ddde6114c6b389e68a4917d99b750

I tested it in a project with an outputPath like the one suggested by Mark and the sources are found. I haven't tested it in a project without an overridden path, but I'd expect it to work.

**Comment by mpeltonen** [comment]
Thanks! I'll test more when I find some spare time...

**Comment by mpeltonen** [comment]
Finally had some time to test this... I didn't find any problems with or without the overridden path so I cherry-picked to my repo too. Thanks again!
