### ISSUE TITLE
gen-idea should automatically run update

### ISSUE THREAD

**Issue by mslinn** [mpeltonen/sbt-idea#160]
Just as compile automatically runs update first, and eclipse does the same, gen-idea should automatically run update before doing its work.

**Comment by mpeltonen** [comment]
It does run update every time (or at least it should do it...). What makes you think it doesn't?

**Comment by mslinn** [comment]
Because I get different results if I type this:

```
sbt gen-idea
```

or this:

```
sbt update gen-idea
```

**Comment by mpeltonen** [comment]
Hmm, so do you get differing Idea metafiles under .idea\* directories with those two commands? Those commands shouldn't make different files, unless there's some bug/feature you just found... (can't test myself just now).

**Comment by ijuma** [comment]
Yeah, update should be indeed run automatically by SBT.
