### ISSUE TITLE
Multi Project setup breaks only one module

### ISSUE THREAD

**Issue by alebon** [mpeltonen/sbt-idea#161]
Hi, 
not sure its a bug of sbt-idea or of the Scala Plugin of IntelliJ.

I got this OS Project with some sub projects: https://github.com/alebon/caladesi-framework
If i run ./caladesi and later on gen-idea everything works fine. The problem arises at the caladesi-common module. It has Scala Facet in IntelliJ but i don't have a context menu to create new Scala classes. The test folder is not marked with color green (as test folder, and i can't set it), too. Packages and classes are not recognized.

Thanks,
Alexej

**Comment by mpeltonen** [comment]
This seems to be related to #152 and #150. It works after you remove the (red) class directory dependencies from caladesi-orientdb module in idea module settings after running gen-idea.

In short, idea gets confused when same project is added both as project reference and class directory reference. And this is a bug in current snapshot.

Trying to find time to fix this soon...

**Comment by alebon** [comment]
Awesome, thanks! I think if you are aware of it and its reported in #150 i can close the issue?

**Comment by mpeltonen** [comment]
Let's keep this open as I have one more project here to test with that the issue gets actually fixed (at least for this project :).

**Comment by alebon** [comment]
OKay :) Additional info, i had to remove all custom folders that contain a full path under module dependencies settings, not only the red ones.

**Comment by mpeltonen** [comment]
You could try now with the latest snapshot. With my short testing with caladesi-framework, the dependencies now generate correctly.

**Comment by alebon** [comment]
Yes, works! :)
Thanks a lot!
