### ISSUE TITLE
Non-snapshot release for SBT 0.12

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#164]
Now that SBT 0.12.0 is out, it would be great to have a non-snapshot release of sbt-idea.

**Comment by mpeltonen** [comment]
Thanks for the notification! Yes, I've been kind of waiting for 0.12.0 for for the 1.1 release. Trying to get into it in the next few days...

**Comment by mpeltonen** [comment]
Done.

**Comment by ijuma** [comment]
Thanks!
