### ISSUE TITLE
Make sbt-classifiers default

### ISSUE THREAD

**Issue by OlegYch** [mpeltonen/sbt-idea#165]
Looks like the issue which was preventing this from working is fixed in 0.11 and 0.12.
If not can you please add a setting to configure the default behavior (it's annoying to have to specify this option every time)?

**Comment by mpeltonen** [comment]
Looks like the fix is included only in 0.12, so setting would probably be better at this point.

**Comment by OlegYch** [comment]
That'd be fine, although i've just discovered aliases in sbt, so it's not that important :).

**Comment by mpeltonen** [comment]
Closing for now. Aliases help to get preferred default for everyone.

For example put the following in ~/.sbtrc:

``` code
alias gen-idea=gen-idea sbt-classifiers
```
