### ISSUE TITLE
sbt 2.9.2 project tries to resolve against Scala 2.9.1 from sbt-and-plugins lib

### ISSUE THREAD

**Issue by rktoomey** [mpeltonen/sbt-idea#168]
Using 1.2.0-SNAPSHOT with latest build of Leda to generate an Idea project for:
https://github.com/novus/salat

Opening Project Structure, I see an error about 

```
Library 'scala-2.9.2' is not used.
```

Examining the project, you see that none of the modules depend on salat-build or use sbt-and-plugins lib, but somehow Idea fails to resolve all Scala-related classes because it sees two possible libs to resolve from, 2.9.1 from sbt-and-plugins, and 2.9.2 from scala-2.9.2 lib.

Same error using Nika; same error with 1.1.0-SNAPSHOT.  You can reproduce it yourself by cloning the project and running `sbt gen-idea`.

As a temporary remedy, you can delete the sbt-and-plugins lib and remove the salat-build module.

Thanks so much for all your hard work on this plugin.  :)

![Error](http://i47.tinypic.com/nebvw6.jpg)

![Error](http://i50.tinypic.com/2qtlsh2.png)

**Comment by OlegYch** [comment]
see http://youtrack.jetbrains.com/issue/SCL-4489

**Comment by OlegYch** [comment]
as a workaround, you can delete all scala-libraries from project except one and invalidate caches

**Comment by rktoomey** [comment]
Yes, thanks  OlegYch, been doing a lot of that lately.

**Comment by mpeltonen** [comment]
Interesting. That "Library 'scala-2.9.2' not used" is not quite correct, as it gets set as Project FCS compiler library, so you can't remove it without compiling breaking.

This looks more like IntelliJ plugin issue, as I think you should (at least in theory...) be able to use different version of scala in different modules. Or at least I can't figure out immediately what could/should be done in sbt-idea to fix this, other than adding a setting to allow disabling sbt build -module generation alltogether?

**Comment by OlegYch** [comment]
A nice workaround would be to allow using the same scala-library in project definition module as in other project modules. I.e. amongst all scala-libraries pick one and use it everywhere.
As for FSC, I don't think there is much value in configuring it since it's better to use idea-sbt-plugin for compilation anyway.

**Comment by mpeltonen** [comment]
Yeah, but that kind of a workaround does not probably work quite well when Scala 2.10 is out and you have 2.10 for your project and 2.9 for sbt, or later even vice versa?

About the fsc -thing, I agree with you about compiling and I use almost exclusively sbt for compiling, but there are apparently quite a few users of fsc with idea :)

**Comment by rktoomey** [comment]
Thanks very much for your help.  Confirmed fixed by http://youtrack.jetbrains.com/issue/SCL-4489.

**Comment by mpeltonen** [comment]
Great to see this fixed in IntelliJ plugin! And thanks for the notification!
