### ISSUE TITLE
Generate directory-based format instead of .ipr file

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#17]
Directory-based format (.idea) is the default format as it makes it easier to share project settings among team members while using automated tools (like sbt-idea-plugin) to generate certain files. Randall Schulz brought this to my attention in the #scala IRC channel.

**Comment by ijuma** [comment]
Suggested fix: http://github.com/ijuma/sbt-idea-plugin/commit/6f687f455e28cb9e6ab8ce414402ac3a33af2e5e

I don't see any benefit in keeping .ipr generation so that is no longer supported after that change. If others disagree, it should be easy to bring it back.

**Comment by RSchulz** [comment]
I can't see why anyone would want the file-based format, but that doesn't mean there's no reason to keep it. It could be driven by a setting in project/idea.properties file.

**Comment by mpeltonen** [comment]
Yes, I too realized some time ago that directory based format would have been better choice from the beginning. Thanks for the patch! I don't see either why someone would absolutely need the ipr version, but if a good use case comes up, that could be a property driven choice.

**Comment by ijuma** [comment]
Mikko has integrated this, so closing.

**Comment by RSchulz** [comment]
Thank you Ismael and Mikko. This will be a real help for us.

**Comment by buka** [comment]
Is it just me or does this change cause the .idea project to now be rooted int the project/ folder? If this is intentional, it's inconsistent with the SBT layout..

**Comment by buka** [comment]
nevermind - my fault - i was inheriting from ParentProject not DefaultProject.
