### ISSUE TITLE
unmanagedClasspath in Runtime

### ISSUE THREAD

**Issue by shiphrah** [mpeltonen/sbt-idea#181]
When adding something like

<code>unmanagedClasspath in Runtime <+= (baseDirectory) map { bd => Attributed.blank(bd / "src" / "main" / "conf") }</code>

to my build.sbt, it is picked up and used when running with sbt. However, the entry is not present as dependency in idea and thus not picked up.

An entry like

<code>libraryDependencies += "org.codehaus.groovy" % "groovy-all" % "2.0.4" % "runtime"</code>

works in both cases.

I'm using 1.2.0-SNAPSHOT. Am I doing something wrong?

Thanks

Jürgen

**Comment by mpeltonen** [comment]
No, you're not wrong. Unmanaged classpath is currently taken only from Compile and Test configurations. Will fix!

**Comment by mpeltonen** [comment]
This should now work with latest (sbt 0.12 version) snapshot.

**Comment by shiphrah** [comment]
Thank you! Works perfectly...
