### ISSUE TITLE
Cannot have the plugin loaded with play 2.0.4

### ISSUE THREAD

**Issue by dkowis** [mpeltonen/sbt-idea#182]
```
[error] java.lang.NoSuchMethodError: org.sbtidea.SbtIdeaPlugin$.ideaSettings()Lscala/collection/Seq;
```

That error appears whenever trying to do _anything_ with sbt.

Here's the full build log in all it's bigness: https://gist.github.com/4111998

**Comment by OlegYch** [comment]
https://play.lighthouseapp.com/projects/82401/tickets/804-namespace-collisions-of-incompatible-typesafe-sbt-idea-fork

**Comment by dkowis** [comment]
Yeah I found that about 10 minutes after I posted this. It's not really this project's fault, so I'm going to close it.

It would be nice to have something in the readme though, because I came here first looking for a solution to the problem.
