### ISSUE TITLE
Provide "provided" scope dependencies to compilation classpath, like sbt does

### ISSUE THREAD

**Issue by timorantalaiho** [mpeltonen/sbt-idea#186]
Typically, ["provided" scope in Maven](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) is used for container-provided dependencies such as the servlet-api. Sbt [borrows the scopes from Maven](http://www.scala-sbt.org/release/docs/Getting-Started/Scopes).

"provided" scope works as expected
- with plain sbt (code compiles and I can see servlet-api when running `show update`
- with direct Idea-Maven-integration

But when we run gen-idea for our project, "provided" dependencies are still missing.

From a quick look to the source code, it seems to me that [the library should appear there with provided scope](https://github.com/mpeltonen/sbt-idea/blob/sbt-0.12/src/main/scala/org/sbtidea/IdeaModuleDescriptor.scala#L89). But in our case, servlet-api ends up in the .iml with "TEST" scope. 

Could it be so that if something gets included both as provided and test scope, it's by chance which one wins?

I would imagine the correct behaviour to be that in the case of the same library ending up in dependencies serveral times, the "strongest" kind of dependency should be the one that ends up in the Idea file. Something like compile > provided > test > runtime?

**Comment by mpeltonen** [comment]
'Provided' dependencies were in theory already included, but if you had the same dependency as transitive dependency of test -scoped dependency, for example, then it was included with test scope. 

A good example is the mentioned servlet-api, as we often have jetty as test dependency, which depends on servlet-api transitively.

As the 'first seen' scope is currently the effective one, we now read 'provided' deps before 'test' deps. Provided should be anyway 'stronger' than test, as provided dependency can be used in compile too.

**Comment by hamnis** [comment]
This affects us as well. Any plans for pushing a new release?

**Comment by mpeltonen** [comment]
The fix is already in latest 1.2.0-SNAPSHOT. I'm also planning to do a release soon, hopefully this week.
