### ISSUE TITLE
JVM options

### ISSUE THREAD

**Issue by fommil** [mpeltonen/sbt-idea#188]
what would I have to add to my `build.sbt` so that JVM options (e.g. log config files) are forwarded to IDEA as default JVM options for all execution targets?

**Comment by jozic** [comment]
I don't think it's implemented now, and I guess that depends on  the plugins installed in your IDEA. Lots of execution targets are brought by different plugins. 
But I guess it can be done for some certain execution targets. 
It probably should be set somewhat like 
    javaOptions in (Test,run) += "-Xmx8G"

**Comment by fommil** [comment]
That doesn't tend to work for me in SBT.

**Comment by mpeltonen** [comment]
Yes, that kind of feature is not implemented and yes, lots of execution targets come with various plugins. Also, the configuration xml for the VM-params is not standard among execution targets, and not all of them even have them. That means it would be a bit hackish case-by-case code if we tried to push them from sbt.

But as @jozic commented, maybe this could be done for some of the most common execution targets like 'Application' and 'Specs2'? Also I'd make that optional and non-default. 

Anyway, they seem to be saved in .idea/workspace.xml, which is not touched by sbt-idea in any way, so you can set the VM-options once in Idea for the targets you use for the project in question and they should stay there even when you re-run gen-idea. So in my opinion this feature would not be a huge win in terms of saving time?

**Comment by fommil** [comment]
It might not save time for people who know to do this, but think of a collaborative project where devops might want to set some flags to the JVM and this is information that just gets lost to new devs who run sbt-idea and don't know to add any properties.
