### ISSUE TITLE
Add support for Android projects

### ISSUE THREAD

**Issue by mpeltonen** [mpeltonen/sbt-idea#191]
As IDEA has nice Android development support, sbt-idea could help in generation of Android facet for Android projects.

**Comment by mpeltonen** [comment]
Initial support is now in the latest snapshot. Because of this: https://github.com/jberkel/android-plugin/issues/147 you need to use a fork of sbt-android-plugin for now. Put this into your plugins.sbt for testing the feature:

``` code
resolvers += "github repo" at "http://mpeltonen.github.com/maven"

resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("com.github.mpeltonen" % "sbt-android-plugin" % "0.6.4-SNAPSHOT")

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.0-SNAPSHOT")
```

**Comment by levinotik** [comment]
This is awesome!

**Comment by alexpolozov** [comment]
This works great, but unfortunately, after switching to sbt-idea 1.3.0-SNAPSHOT and sbt-android-plugin 0.6.3-SNAPSHOT I lost the ability to build Android packages:

```
> android:package-debug

[info] Wrote D:\PROJECTS\Scala_Android\hello\target\scala-2.9.2\src_managed\main\scala\apskim\android\hello\TR.scala
[trace] Stack trace suppressed: run 'last Hello/android:proguard' for the full output.
[error] (Hello/android:proguard) java.lang.NoSuchMethodError: proguard.ConfigurationParser.<init>([Ljava/lang/String;)V
[error] Total time: 0 s, completed 24.12.2012 18:28:47
> > last Hello/android:proguard
java.lang.NoSuchMethodError: proguard.ConfigurationParser.<init>([Ljava/lang/String;)V
    at AndroidInstall$$anonfun$proguardTask$1.apply(AndroidInstall.scala:154)
    at AndroidInstall$$anonfun$proguardTask$1.apply(AndroidInstall.scala:115)
    at sbt.Scoped$$anonfun$hf9$1.apply(Structure.scala:585)
    at sbt.Scoped$$anonfun$hf9$1.apply(Structure.scala:585)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
[error] (Hello/android:proguard) java.lang.NoSuchMethodError: proguard.ConfigurationParser.<init>([Ljava/lang/String;)V
```

**Comment by mpeltonen** [comment]
Hmm, android:package-debug works for me with the plugins.sbt above: https://gist.github.com/4372870

Looks like some problem with the classpath, but I have no suggestions at this point. I guess you changed the imports in your build files to include the package: 

``` code
import org.scalasbt.androidplugin._
import org.scalasbt.androidplugin.AndroidKeys._
```

**Comment by alexpolozov** [comment]
Finally figured it out. The published android-plugin for some reason launches ProGuard 4.6, although the latest source has support for ProGuard 4.8. I publish-local:ed the android-plugin built from the latest sources and your patch applied, set its version to 0.6.3.0.1, and now everything seems to work.

**Comment by mpeltonen** [comment]
Ok, great. I need to check why so.

**Comment by levinotik** [comment]
Hmm. Had this working before, so not sure what changed. If my plugins.sbt looks like this:

> resolvers += Resolver.url("scalasbt releases", new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin->releases"))(Resolver.ivyStylePatterns)
> 
> resolvers += "github repo" at "http://mpeltonen.github.com/maven"
> 
> resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"
> 
> addSbtPlugin("com.github.mpeltonen" % "sbt-android-plugin" % "0.6.3-SNAPSHOT")
> 
> addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.3.0-SNAPSHOT")

..then I get an sbt error that "not found: object AndroidKeys ...import AndroidKeys._"

But everything works with the default android plugin, i.e.

> resolvers += Resolver.url("scalasbt releases", new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
> 
> addSbtPlugin("org.scala-sbt" % "sbt-android-plugin" % "0.6.2")

**Comment by mpeltonen** [comment]
Looks like you have the imports wrong(?), i.e. you have to change the import paths when using the fork:

``` code
import org.scalasbt.androidplugin._
import org.scalasbt.androidplugin.AndroidKeys._
```

**Comment by levinotik** [comment]
What is the Build.scala supposed to look like for an Android project when using the snapshots? When I changed to the org.scalasbt.androidplugin._, org.scalasbt.androidplugin.AndroidKeys._ imports my Build.scala looks like this (from the auto-generated n8han/giter8 template):

``` scala
import sbt._

import org.scalasbt.androidplugin._
import org.scalasbt.androidplugin.AndroidKeys._

object General {
  val settings = Defaults.defaultSettings ++ Seq (
    name := "my-android-project",
    version := "0.1",
    versionCode := 0,
    scalaVersion := "2.9.2",
    platformName in Android := "android-16"
  )

  val proguardSettings = Seq (
    useProguard in Android := true
  )

  lazy val fullAndroidSettings =
    General.settings ++
    AndroidProject.androidSettings ++
    TypedResources.settings ++
    proguardSettings ++
    AndroidManifestGenerator.settings ++
    AndroidMarketPublish.settings ++ Seq (
      keyalias in Android := "change-me",
      libraryDependencies += "org.scalatest" %% "scalatest" % "1.8" % "test"
    )
}

object AndroidBuild extends Build {

  lazy val main = Project (
    "my-android-project",
    file("."),
    settings = General.fullAndroidSettings
  )

  lazy val tests = Project (
    "tests",
    file("tests"),
    settings = General.settings ++
               AndroidTest.androidSettings ++
               General.proguardSettings ++ Seq (
      name := "my-android-projectTests"
    )
  ) dependsOn main
}

```

Which causes these issues:

```
[info] Compiling 1 Scala source to /Users/levinotik/Dev/android/my-android-project/project/target/scala-2.9.2/sbt-0.12/classes...
[error] /Users/levinotik/Dev/android/my-android-project/project/Build.scala:8: not found: value name
[error]     name := "my-android-project",
[error]     ^
[error] /Users/levinotik/Dev/android/my-android-project/project/Build.scala:8: reassignment to val
[error]     name := "my-android-project",
[error]          ^
[error] /Users/levinotik/Dev/android/my-android-project/project/Build.scala:9: not found: value version
[error]     version := "0.1",
[error]     ^
[error] /Users/levinotik/Dev/android/my-android-project/project/Build.scala:9: reassignment to val
[error]     version := "0.1",
[error]             ^
[error] /Users/levinotik/Dev/android/my-android-project/project/Build.scala:11: not found: value scalaVersion
[error]     scalaVersion := "2.9.2",
[error]     ^
[error] /Users/levinotik/Dev/android/my-android-project/project/Build.scala:11: reassignment to val
[error]     scalaVersion := "2.9.2",
[error]                  ^
[error] 6 errors found
[error] (compile:compile) Compilation failed
```

Obviously, I'm doing something really wrong here.

**Comment by levinotik** [comment]
It seemed to all "just work" if I just removed those keys.

**Comment by levinotik** [comment]
How do I get the jars in /libs to be recognized?

**Comment by mpeltonen** [comment]
You need also 'import Keys._' after 'import sbt._' for the name, version, scalaVersion etc. to be found.

**Comment by mpeltonen** [comment]
As for the /libs, it should be 'lib', or see http://www.scala-sbt.org/release/docs/Detailed-Topics/Library-Management#manual-dependency-management

**Comment by levinotik** [comment]
@mpeltonen Thanks a lot. Appreciate it. I managed to get the dependency by doing:

``` scala
lazy val fullAndroidSettings =
    General.settings ++
      AndroidProject.androidSettings ++
      TypedResources.settings ++
      proguardSettings ++
      AndroidManifestGenerator.settings ++
      AndroidMarketPublish.settings ++ Seq (
      keyalias in Android := "change-me",//,
      proguardInJars in Android ++= ((file("libs") ** "*.jar") get),
      libraryDependencies ++= Seq(
        "org.json4s" %% "json4s-native" % "3.0.0",
        "org.scalatest"     %% "scalatest"        % "1.6.1"        % "test"
      )
      //      libraryDependencies += "org.scalatest" %% "scalatest" % "1.8" % "test"
    )
```

But I'm going to try lib as well. Currently having an annoying issue in using json4s where my case classes don't seem to be properly compiled by scalac.

**Comment by levinotik** [comment]
@mpeltonen so i need to add something like `unmanagedBase <<= baseDirectory { base => base / "lib" }` or if its `lib` then it'll just work?

**Comment by mpeltonen** [comment]
Yes, `base / "libs"` in that expression in your case should do the trick, or move jars to /lib.

**Comment by levinotik** [comment]
Appreciate the help @mpeltonen Not sure if this is or jberkel's plugin is the place to ask, but I'm having some issues with dependencies that themselves rely on the Android compatibility package. For instance, I've added:

``` scala

      libraryDependencies ++= Seq(
        "com.viewpagerindicator" % "library" % "2.4.1" artifacts(Artifact("library", "apklib", "apklib")),
        "android" % "compatibility-v4" % "r3-SNAPSHOT"
      )
```

To my Build.scala. No idea if that was the right way to do it. In any event, this successfully adds the VPI library, but when I try to use (for instance) the FragmentPagerAdapter from the ACL, IntelliJ sees that I have that class, but complains that FragmentPagerAdapter itself refers to "unspecified value parameter Fragment", which is the v4 support Fragment that FragmentPagerAdapter requires. It seems like this is a case where I'd normally mark the library project's dependency as exported so my project can inherit the jars it depends on, but I'm not sure how to do that here. 

Hope that wasn't too confusing and I'd really appreciate any help.

**Comment by mpeltonen** [comment]
I don't quite understand the problem from the description, as I haven't came across a similar situation.

So can you fix things in IntelliJ after gen-idea by doing something by hand? If so, what exactly you need to do?

A complete sample project demonstrating the problem would be handy.

**Comment by levinotik** [comment]
@mpeltonen Seemed to have fixed the issue. Newish to Scala and forgot that I needed something like:

`class MyAdapter(fm: FragmentManager) extends FragmentPagerAdapter(fm)`

My issue now is that when I include a library project and reference a custom view from that lib project in my layouts, my app crashes with error inflating the xml. 

```
E/AndroidRuntime(32631): java.lang.RuntimeException: Unable to start activity ComponentInfo{my.last.attempt/activities.StreamsActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class com.viewpagerindicator.TitlePageIndicator
E/AndroidRuntime(32631):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2088)
E/AndroidRuntime(32631):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2113)
E/AndroidRuntime(32631):    at android.app.ActivityThread.access$700(ActivityThread.java:139)
E/AndroidRuntime(32631):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1224)
E/AndroidRuntime(32631):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(32631):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(32631):    at android.app.ActivityThread.main(ActivityThread.java:4918)
E/AndroidRuntime(32631):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(32631):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(32631):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
E/AndroidRuntime(32631):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
E/AndroidRuntime(32631):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(32631): Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.viewpagerindicator.TitlePageIndicator
E/AndroidRuntime(32631):    at android.view.LayoutInflater.createView(LayoutInflater.java:596)
E/AndroidRuntime(32631):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
E/AndroidRuntime(32631):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
E/AndroidRuntime(32631):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime(32631):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime(32631):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
E/AndroidRuntime(32631):    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:306)
E/AndroidRuntime(32631):    at android.app.Activity.setContentView(Activity.java:1901)
E/AndroidRuntime(32631):    at activities.StreamsActivity.onCreate(StreamsActivity.scala:43)
E/AndroidRuntime(32631):    at android.app.Activity.performCreate(Activity.java:5048)
E/AndroidRuntime(32631):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
E/AndroidRuntime(32631):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2052)
E/AndroidRuntime(32631):    ... 11 more
E/AndroidRuntime(32631): Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
E/AndroidRuntime(32631):    at java.lang.Class.getConstructorOrMethod(Class.java:460)
E/AndroidRuntime(32631):    at java.lang.Class.getConstructor(Class.java:431)
E/AndroidRuntime(32631):    at android.view.LayoutInflater.createView(LayoutInflater.java:561)
E/AndroidRuntime(32631):    ... 22 more
```

Same goes for the ACL ViewPager class referenced in XML...

**Comment by mpeltonen** [comment]
Jan merged my pull requests to android-plugin master, so now you can use sbt-idea's Android support with official android-plugin snapshot and sbt-idea 1.5.0-SNAPSHOT. Put this to project/plugins.sbt:

``` code
resolvers += Resolver.url("scalasbt releases", new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-snapshots"))(Resolver.ivyStylePatterns)

resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("org.scala-sbt" % "sbt-android-plugin" % "0.6.3-20130429-SNAPSHOT")

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.0-SNAPSHOT")
```

**Comment by fokot** [comment]
Hi @mpeltonen are you using scala version 2.9.2 and sbt 12? It doesn't work for me. But I'm ok with using scala 2.10.1 but that doesn't work neither. 

Look I got this error:
[error](*:update) sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;1.5.0-SNAPSHOT: not found

What am I doing wrong?

**Comment by mpeltonen** [comment]
@fokot: My sample setup was missing Sonatype snapshots repository where 1.5.0-SNAPSHOT is. That's why you got that error. Try adding it (I added it to example config above).

About scala version, sbt 0.12 itself (i.e. the sbt build definitions) require 2.9.2, but for your project code both 2.9.2 and 2.10 should work (whatever scalaVersion you declare in build definition).

**Comment by fokot** [comment]
Thanks @mpeltonen it works! And for using with scala 2.10.1 is this the best way? (I know that this is sbt question and not your plugin thing but I'm newbie)

``` scala
import Defaults.sbtPluginExtra

resolvers += Resolver.url("scalasbt releases", new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-snapshots"))(Resolver.ivyStylePatterns)

resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies += sbtPluginExtra("org.scala-sbt" % "sbt-android-plugin" % "0.6.3-20130429-SNAPSHOT", "0.12", "2.9.2")

libraryDependencies += sbtPluginExtra("com.github.mpeltonen" % "sbt-idea" % "1.5.0-SNAPSHOT", "0.12", "2.9.2")

scalaVersion := "2.10.1"
```

**Comment by mpeltonen** [comment]
@fokot: Do not put the scalaVersion in plugins.sbt (or any .sbt on projects/ -dir because that way you declare scalaVersion for the sbt project definition and sbt 0.12 does not support Scala 2.10 for project definition). 

You need to set it either in build.sbt in your project root directory, or .scala format project definition in <project root>/project -directory.  

See http://www.scala-sbt.org/release/docs/Getting-Started/Basic-Def.html#sbt-vs-scala-definition

**Comment by fokot** [comment]
Thanks, I changed that and I use 2.10.1 only in my app for 2.9.2 for plugins. Btw. it works and loads in phone :)

**Comment by fxthomas** [comment]
@mpeltonen : When do you release sbt-idea 1.5? I tweaked it a little to handle my latest changes and fixes in sbt-android -- handling Proguard, preloaded Scala libraries and ApkLib dependencies correctly, among others.

**Comment by mpeltonen** [comment]
Still waiting/hoping for a stable release of sbt-android-plugin with https://github.com/jberkel/android-plugin/issues/147 before release.

**Comment by fxthomas** [comment]
Okay, so :
- I hope we'll be able to release something in the following weeks.
  
  If I could get both the latest sbt-android and sbt-idea tested by a few outside people before that happens, it would be great.
- How do you currently handle multiple configurations (Release, Debug,...) in sbt-idea?
  
  The new sbt-android will support 3 configurations by default : **Development** (which skips Proguard but requires Scala to be preloaded on a rooted device/emulator with the `preload` command), **Debug** (which builds a full APK that runs on any stock device) and **Release** (which prepares the APK for Market release). Right now, sbt-idea obviously picks only the default configuration from Compile -- which will be either Development or Debug. IntelliJ is therefore primarily for development, and you can build additional packages using SBT when needed. How does that sound?
- As a side note, we found out yesterday that IntelliJ could be configured rather easily to build APKs using a SBT task, but run them using its own Android facet, and even use the debugger and run instrumentation tests from the IDE, so the matter of additional configurations can be solved if needed even if it's not integrated in the plugin.

**Comment by mpeltonen** [comment]
> How do you currently handle multiple configurations (Release, Debug,...) in sbt-idea?

Not in any way. I need to understand first what this means in android plugin config and how those configurations should affect the generated IntelliJ Android facet.

**Comment by fxthomas** [comment]
I think I'll juste leave it as it is then. The default will be fine for now!

**Comment by mpeltonen** [comment]
Now sbt-android-0.6.4 seems to exist, so with latest sbt-idea snapshot android support can be enabled with:

``` code
resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("org.scala-sbt" % "sbt-android" % "0.6.4")

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.0-SNAPSHOT")
```

imports in your build file should be:

``` code
import sbtandroid._
import sbtandroid.AndroidKeys._
```

**Comment by i-am-the-slime** [comment]
When I try that I get:
sbt.ResolveException: unresolved dependency: org.scala-sbt#sbt-android-plugin;0.6.4: not found

**Comment by mpeltonen** [comment]
What is your sbt version? 0.11 (or 0.13) maybe?

It is here, but only for sbt 0.12: http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt-android/scala_2.9.2/sbt_0.12/0.6.4/

**Comment by i-am-the-slime** [comment]
> sbt-version
> [info] 0.12.0-RC4
> Oh it was my fault, sorry I kept the old "sbt-android-plugin" instead of "sbt-android"

**Comment by mpeltonen** [comment]
Closing this as initial stable version with Android support is released (http://notes.implicit.ly/post/56635172083/sbt-idea-1-5-1)
