### ISSUE TITLE
gen-idea failure, fails to create project file

### ISSUE THREAD

**Issue by PhilAndrew** [mpeltonen/sbt-idea#194]
It fails to write the module so that when I startup Idea it says:
Cannot convert project: /Users/orsa/home/projects/reverse/.idea_modules/default-35db85.iml: Error on line 9: XML document structures must start and end within the same entity.

plugins.sbt
http://pastebin.com/1LxPj9hZ

SBT build file, build.sbt:
http://pastebin.com/KS6Y7nwQ

Log file here:
http://pastebin.com/vFwcGtVj

**Comment by PhilAndrew** [comment]
I commented out the ScalaC Options in the build.sbt and it works now

// scalacOptions ++= Seq("-Xexperimental", "-unchecked", "–deprecation")

**Comment by jozic** [comment]
If you change "–deprecation" to "-deprecation" it will work as well. The issue here is that this char "–" is not "-" and it's not in ISO-8859-1, which is currently used by sbt-idea for xml files saving.

**Comment by mpeltonen** [comment]
Closing, as the problem seems to be in encoding as noticed by @jozic
