### ISSUE TITLE
Set language level from scalaVersion

### ISSUE THREAD

**Issue by mdekstrand** [mpeltonen/sbt-idea#195]
Recent versions of the Scala IDEA plugin support a Scala language level, like the Java language level. It would be useful to set this; it can probably be at least set by default from the `scalaVersion` setting, although some additional logic or manual configuration may be needed for alternative versions (e.g. Scala 2.10 Virtual).

**Comment by analytically** [comment]
+1

**Comment by mpeltonen** [comment]
Good suggestion. Thanks for the heads up about the new setting!

**Comment by mpeltonen** [comment]
Implemented in latest snapshot.
