### ISSUE TITLE
1.3.0 snapshot not accessible.

### ISSUE THREAD

**Issue by pkmishra** [mpeltonen/sbt-idea#199]
Not accessible as per the Readme.  - https://oss.sonatype.org/content/repositories/snapshots/com/github/mpeltonen/

**Comment by pkmishra** [comment]
looks like something was wrong at my end.

**Comment by pkmishra** [comment]
Ah. This is not working for scala 2.10.0.

**Comment by avaranovich** [comment]
Just wondering, is that possible to make it work with scala 2.10 and sbt 0.13?

**Comment by avaranovich** [comment]
I use this as a workaround with scala 2.10 and sbt 0.13

```
libraryDependencies += sbtPluginExtra(
   m = "com.github.mpeltonen" % "sbt-idea" % "1.3.0-SNAPSHOT", // Plugin module name and version
   sbtV = "0.12",    // SBT version
   scalaV = "2.9.2"    // Scala version compiled the plugin
)
```

**Comment by pkmishra** [comment]
Thanks @avaranovich It worked. Still keeping it open for tracking purpose.

**Comment by mpeltonen** [comment]
Yeah, sbt 0.13 support branch is not done yet.

**Comment by alexpolozov** [comment]
Still not accessible. sbt 0.12, scala 2.10.

**Comment by mpeltonen** [comment]
Is there an easy way to test sbt 0.13? I was planning to add the 0.13 branch and snapshot after first non-snapshot build of sbt 0.13 is available.

Setting sbt.version to 0.13.0-SNAPSHOT did not seem to work, and publish-local:ing 0.13 branch of xsbt repo ended up with some errors I didn't have time to investigate.

**Comment by pkmishra** [comment]
I have not used it with sbt 0.13 however I was finally able to setup things for scala 2.10 and sbt 0.12.1. Please see details here . http://pkmishra.github.com/productivity/2013/01/16/scala-sbt-and-intellij-idea-boilerplate/

**Comment by jozic** [comment]
Mikko, could you please publish an artifact for scala 2.10?
there is sbt-idea_2.9.2_0.12 in sonatype repo, but nothing for 2.10

**Comment by mpeltonen** [comment]
This issue seems to be confusing two things, sbt 0.12 and sbt 0.13. Please correct me if I'm wrong, but sbt 0.12 supports Scala 2.9.2 for build definition, and only sbt 0.13 supports 2.10 (http://www.scala-sbt.org/0.13.0-SNAPSHOT/docs/Community/ChangeSummary_0.13.0.html). That also means that sbt-idea doesn't need to be published for sbt 0.12/Scala 2.10 combination, right?

That doesn't mean that you can't use Scala 2.10 for the _project code_ with sbt 0.12. The 2.9.2_0.12 version should download just fine even if you set scalaVersion to 2.10.0 in your project definition?

**Comment by pkmishra** [comment]
That's right Mikko. We are on the same page.

**Comment by mpeltonen** [comment]
Meaning also that the sbtPluginExtra stuff in your blog should be redundant, i.e. not needed?

**Comment by pkmishra** [comment]
Well if we want to use sbt 0.12 with scala 2.10.0 you can specify scalaVersion in build file see this - https://groups.google.com/forum/?fromgroups=#!topic/simple-build-tool/0LLCYZM2uno. This is a work around until once upgrades to sbt 0.13. So We can close this issue if you want.

**Comment by mpeltonen** [comment]
Just to be sure, are we talking about using Scala 2.10 for the sbt project definition or for your actual project code? I guess we're talking about the sbt project definition code?

I don't see the point in using it for sbt project definition with sbt 0.12, as it is not officially supported by sbt 0.12. And for the actual project code, Scala 2.10 can be used with sbt 0.12 without any workarounds.

**Comment by pkmishra** [comment]
Yeah makes sense. Closing the issue assuming you will publish it for sbt 0.13 and scala 2.10.0 combination.
