### ISSUE TITLE
Feature: Add option for excluding "lib_managed" subdirectory

### ISSUE THREAD

**Issue by sirthias** [mpeltonen/sbt-idea#20]
It would be nice if the plugin could (optionally) exclude the "lib_managed" sub directories underneath the module directories...

**Comment by mpeltonen** [comment]
Could you be more specific on what you would like to achieve? Plugin currently adds every managed jar under lib_managed as module library, but not any subdirectory of lib_managed as such.

Do you mean an option to exclude all managed dependencies?!

**Comment by sirthias** [comment]
No, its only a small improvement I'm asking for.
My project has a bunch of module subprojects whose directories each contain a "lib_managed" folder, where sbt keeps the managed libraries.
Since these directories are "internal" I think they should be invisible in the IDEA project view. This is easily achieved by marking them as "excluded" in the "Sources" tab of the "Project Structure/Module" dialog...

**Comment by mpeltonen** [comment]
Ah, I see. Yes, that should probably be optional (i.e. property driven), as I can imagine someone finding it useful that managed dependencies are visible under projects.

**Comment by mpeltonen** [comment]
Add 'exclude.libmanaged.folders' property to allow hiding lib_managed folders in IDEA project view. Closed by 9cd053d087f2c267bb6345e40572b8000ba2249e.

**Comment by sirthias** [comment]
Excellent. Thx for the ultra-fast implementation!
