### ISSUE TITLE
sbt-idea fails to download using https through proxy

### ISSUE THREAD

**Issue by fernandoracca** [mpeltonen/sbt-idea#204]
I can't get SBT 1.3.0-SNAPSHOT (which is the only one that works with scala 2.10 and sbt 0.12.2) using https through a proxy.

If i only specify http.host, password and so on, it shows a connection timeout on the oss sonatype repository       

"Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/",

Specifying https parameters, i get the following output:

[info] Resolving com.typesafe.sbteclipse#sbteclipse-plugin;2.1.1 ...
  [info] Resolving com.typesafe.sbteclipse#sbteclipse-core;2.1.1 ...
  [info] Resolving org.scalaz#scalaz-core_2.9.2;6.0.4 ...
  [info] Resolving org.scala-lang#scala-library;2.9.2 ...
  [info] Resolving com.github.mpeltonen#sbt-idea;1.3.0-SNAPSHOT ...
  [info] Resolving com.eed3si9n#sbt-man;0.1.0 ...
  [info] Resolving net.databinder#dispatch-core_2.9.1;0.8.5 ...
  [info] Resolving org.apache.httpcomponents#httpclient;4.1 ...
  [info] Resolving org.apache.httpcomponents#httpcore;4.1 ...
  [info] Resolving commons-logging#commons-logging;1.1.1 ...
  [info] Resolving commons-codec#commons-codec;1.4 ...
  [info] Resolving net.databinder#dispatch-lift-json_2.9.1;0.8.5 ...
  [info] Resolving net.databinder#dispatch-http_2.9.1;0.8.5 ...
  [info] Resolving net.databinder#dispatch-futures_2.9.1;0.8.5 ...
  [info] Resolving net.liftweb#lift-json_2.9.0-1;2.4-M3 ...
  [info] Resolving com.thoughtworks.paranamer#paranamer;2.3 ...
  [info] Resolving org.scala-lang#scalap;2.9.0-1 ...
  [info] Resolving org.scala-lang#scala-compiler;2.9.2 ...
  [info] Resolving org.scala-sbt#sbt;0.12.2 ...
  [info] Resolving org.scala-sbt#main;0.12.2 ...
  [info] Resolving org.scala-sbt#actions;0.12.2 ...
  [info] Resolving org.scala-sbt#classpath;0.12.2 ...
  [info] Resolving org.scala-sbt#launcher-interface;0.12.2 ...
  [info] Resolving org.scala-sbt#interface;0.12.2 ...
  [info] Resolving org.scala-sbt#io;0.12.2 ...
  [info] Resolving org.scala-sbt#control;0.12.2 ...
  [info] Resolving org.scala-sbt#completion;0.12.2 ...
  [info] Resolving org.scala-sbt#collections;0.12.2 ...
  [info] Resolving jline#jline;1.0 ...
  [info] Resolving org.scala-sbt#api;0.12.2 ...
  [info] Resolving org.scala-sbt#compiler-integration;0.12.2 ...
  [info] Resolving org.scala-sbt#incremental-compiler;0.12.2 ...
  [info] Resolving org.scala-sbt#logging;0.12.2 ...
  [info] Resolving org.scala-sbt#process;0.12.2 ...
  [info] Resolving org.scala-sbt#compile;0.12.2 ...
  [info] Resolving org.scala-sbt#persist;0.12.2 ...
  [info] Resolving org.scala-tools.sbinary#sbinary_2.9.0;0.4.0 ...
  [info] Resolving org.scala-sbt#classfile;0.12.2 ...
  [info] Resolving org.scala-sbt#compiler-ivy-integration;0.12.2 ...
  [info] Resolving org.scala-sbt#ivy;0.12.2 ...
  [info] Resolving org.apache.ivy#ivy;2.3.0-rc1 ...
  [info] Resolving com.jcraft#jsch;0.1.46 ...
  [info] Resolving commons-httpclient#commons-httpclient;3.1 ...
  [info] Resolving commons-logging#commons-logging;1.0.4 ...
  [info] Resolving commons-codec#commons-codec;1.2 ...
  [info] Resolving org.scala-sbt#run;0.12.2 ...
  [info] Resolving org.scala-sbt#task-system;0.12.2 ...
  [info] Resolving org.scala-sbt#tasks;0.12.2 ...
  [info] Resolving org.scala-sbt#tracking;0.12.2 ...
  [info] Resolving org.scala-sbt#cache;0.12.2 ...
  [info] Resolving org.scala-sbt#testing;0.12.2 ...
  [info] Resolving org.scala-sbt#test-agent;0.12.2 ...
  [info] Resolving org.scala-tools.testing#test-interface;0.5 ...
  [info] Resolving org.scala-sbt#command;0.12.2 ...
  [info] Resolving org.scala-sbt#compiler-interface;0.12.2 ...
  [info] Resolving org.scala-sbt#precompiled-2_8_2;0.12.2 ...
  [info] Resolving org.scala-sbt#precompiled-2_10_0;0.12.2 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;1.3.0-SNAPSHOT: java.util.NoSuchElementException
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.mpeltonen:sbt-idea:1.3.0-SNAPSHOT (sbtVersion=0.12, scalaVersion=2.9.2)
[warn]
sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;1.3.0-SNAPSHOT: java.util.NoSuchElementException

Any ideas?

**Comment by mpeltonen** [comment]
So release versioned plugins do download, but SNAPSHOTs don't? Or is the problem only sonatype snapshots repository? Anyway, I don't think this is sbt-idea specific problem only?

Also, 1.2.0 version should work with sbt 0.12.2 and Scala 2.10.0, unless you need some specific fix that only exists in the snapshot?

**Comment by fernandoracca** [comment]
Removing this repository from the .sbt/repositories file actually fixed it.   

sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots

Thanks!
