### ISSUE TITLE
Problem with "with-sources=yes".

### ISSUE THREAD

**Issue by larssn** [mpeltonen/sbt-idea#206]
Whats the status on this project?
Asking because it doesn't seem to play very nice with Play 2.1 and Idea 12.0.4.
I know Play integrates with sbt-idea and is invoked by calling "idea with-sources=yes".

Sources doesn't appear to get downloaded, I get a lot of:
[warn]  [NOT FOUND  ] org.apache.ant#ant;1.8.2!ant.jar(src) (98ms)
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/apache/ant/ant/1.8.2/ant-1.8.2-sources.jar
.. for pretty much every file.

Also, when observing the project structure for the created Idea project, there are some problems with the Scala facets not referencing the correct scala-compiler libraries, and some more insignificant problems with the excluded project folders being named after older versions of Scala (pre 2.10).

I don't know where the problem lies. Here or with Play. Play devs doesn't seem to acknowledge it: http://play.lighthouseapp.com/projects/82401/tickets/598-idea-with-sources-does-not-fetch-sources

Ps. I'm pretty new to this stuff, so I hope I make sense.

**Comment by dchuiko** [comment]
I also have a similar problem with the same environment. All libraries attached to an idea project doesn't have attached sources although they are present in ivy repository.

**Comment by kclay** [comment]
you can try `sbt gen-idea sbt-classifiers`

**Comment by mpeltonen** [comment]
To answer your question, the status is that it works pretty well for me and many others. 

Unfortunately I've not used Play myself at all, so I'm not familiar with the potential issues it has with Idea. All I know is that it includes typesafe's fork of sbt-idea for generating Idea files, and I guess you should use it with Play projects, instead of sbt-idea.

**Comment by larssn** [comment]
Thanks for the answer.

So apparently it IS their problem. I assume its just not a priority for them.
You should give Play a go though, its pretty cool. :)

**Comment by jozic** [comment]
since play 2.1 they've changed package names, so there should no be collisions between two versions of the plugin.  I personally use original sbt-idea with Play. It works fine for me

**Comment by dchuiko** [comment]
Thanks for the answers! Using original sbt-idea plugin with Play solved the problem.

**Comment by mpeltonen** [comment]
Ok, good to know!

**Comment by mpeltonen** [comment]
Closing, as this is about Play's version.
