### ISSUE TITLE
wrong src_managed folder added as source folders

### ISSUE THREAD

**Issue by francisdb** [mpeltonen/sbt-idea#209]
I use the sbt-xjc plugin that generates its sources in  target/scala-xx/src_managed/main/xjc which is then picked up by sbt as source folder

The idea plugin however adds target/scala-xx/src_managed/main as source folder causing all my packages to be invalid. (java)

**Comment by mpeltonen** [comment]
Small sample project demonstrating the problem would be nice!

**Comment by francisdb** [comment]
I'll take care of it later today, thanks for following up

**Comment by francisdb** [comment]
https://github.com/francisdb/stuff/tree/master/sbt-idea-issue209

```
sbt
...
> run
[info] Running com.test.MyApp
John
[success] Total time: 0 s, completed Apr 9, 2013 11:56:15 PM
> gen-idea
...
```

now open the project in idea and open Main.scala, it will complain about the package for the generated sources that it can not resolve because the wrong folder is being added as source folder

**Comment by mpeltonen** [comment]
Try 1.4.0-SNAPSHOT now. Should be fixed there.

**Comment by francisdb** [comment]
Just checked the docs to be sure the patch is correct:
http://www.scala-sbt.org/release/docs/Howto/generatefiles.html

Thanks for fixing this!

**Comment by francisdb** [comment]
Might be a good idea to mention that you first have to build the project before using the plugin so that all generated code folders are picked up correctly

**Comment by mpeltonen** [comment]
Good point! We might even run 'managed-sources' task within 'gen-idea'? That would ensure all folders are in place.

**Comment by mpeltonen** [comment]
'managed-sources' is now automatically run from within 'gen-idea' if the project has generated sources, so that all folders are available.

**Comment by francisdb** [comment]
great :+1:

**Comment by mpeltonen** [comment]
Fixed in latest snapshot.

**Comment by analytically** [comment]
This fails for me. My project has multiple subprojects.

1.3.0 generated

```
<sourceFolder url="file://$MODULE_DIR$/../api/target/scala-2.10/src_managed/main" isTestSource="false" />
```

Using 1.4.0 this isn't there anymore.

**Comment by francisdb** [comment]
According to http://www.scala-sbt.org/release/docs/Howto/generatefiles.html generated sources should be in a subfolder of that folder

But the plugin should maybe be a bit smarter and use the sourceGenerators to set up source folders?

**Comment by mpeltonen** [comment]
@analytically: Which plugin you are using that produces your managed sources? 

I'd say that the plugin does not work "correctly", and produces sources directly under src_managed/main, and not into a plugin specific subdirectory as the documentation (http://www.scala-sbt.org/release/docs/Howto/generatefiles.html) suggests. From 1.4.0 on, only subdirectories under src_managed/main (or src_managed/test) are added. 

I wonder if there should be logic to include src_managed/main in case it does exists but no subdirectories under it? Or can you get the exact directories from sourceGenerators key somehow? 

What if you use two plugins and the first one outputs to /main and second one to /main/myplugin? I think this does not work in Idea at all?

**Comment by analytically** [comment]
I'm using SBT BuildInfo:
https://github.com/sbt/sbt-buildinfo

I'll log an issue there as well.
