### ISSUE TITLE
Migration to Scala 2.8.x 

### ISSUE THREAD

**Issue by pfuller** [mpeltonen/sbt-idea#21]
Hi,

I've recently migrated my projects to Scala 2.8.0 but unfortunately the plugin doesn't appear to work with this version.  Are there any plans to move to Scala 2.8.0 ?

If not any idea's what changes would be required to do this as I might have a go myself.

Thanks,

Paul.

**Comment by mpeltonen** [comment]
Sbt 0.7.x, which plugin supports, does not support Scala 2.8. I.e. your project definition must be 2.7.7 (def.scala.version in build.properties)

You _can_, however, definitely use 2.8 in your project code. Just define 'build.scala.versions=2.8.0' in your build.properties, and sbt-idea-plugin will create Intellij configuration just fine and use Scala 2.8 for building your project.

Or did I misunderstand something?

**Comment by pfuller** [comment]
Thanks, my project definition is 2.8.0 so I'll move this back to 2.7.7 and give this a try

**Comment by pfuller** [comment]
All works fine now, great plugin, thanks

**Comment by mpeltonen** [comment]
Great, thanks!

**Comment by ghost** [comment]
For the benefit of those searching for the following error message:

Error during sbt execution: sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea-processor_2.8.0;0.1-SNAPSHOT: not found

Putting the following in build.properties:

def.scala.version=2.7.7
build.scala.version=2.8.0

... solved the problem for me too. Thanks!
