### ISSUE TITLE
Problems with idea 12.04

### ISSUE THREAD

**Issue by antonkulaga** [mpeltonen/sbt-idea#213]
Seems like in 12.04 idea slightly changed its format as I am getting rather weird errors when I make my projects generated by gen-idea in idea 12.04

**Comment by mpeltonen** [comment]
What kind of errors do you get? I can't reproduce any errors with Idea 12.1 CE and latest Scala plugin 0.7.213.

**Comment by antonkulaga** [comment]
There were some errors in IDEA, I reported them and they were resolved.
