### ISSUE TITLE
Download successful but dont have gen-idea

### ISSUE THREAD

**Issue by gaoyike** [mpeltonen/sbt-idea#214]
Here is the log 
[info] Resolving com.github.mpeltonen#sbt-idea;1.4.0-SNAPSHOT ...
[info] Resolving commons-io#commons-io;2.0.1 ...
[info] Resolving org.eclipse.jetty#jetty-webapp;8.0.4.v20111024 ...
[info] Resolving org.eclipse.jetty#jetty-xml;8.0.4.v20111024 ...
[info] Resolving org.eclipse.jetty#jetty-util;8.0.4.v20111024 ...
[info] Resolving org.eclipse.jetty#jetty-servlet;8.0.4.v20111024 ...
[info] Resolving org.eclipse.jetty#jetty-security;8.0.4.v20111024 ...
[info] Resolving org.eclipse.jetty#jetty-server;8.0.4.v20111024 ...
[info] Resolving org.mortbay.jetty#servlet-api;3.0.20100224 ...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.0.4.v20111024 ...
[info] Resolving org.eclipse.jetty#jetty-http;8.0.4.v20111024 ...
[info] Resolving org.eclipse.jetty#jetty-io;8.0.4.v20111024 ...
[info] Done updating.

> gen-idea
> [error] Not a valid command: gen-idea
> [error] Not a valid project ID: gen-idea
> [error] Expected ':'
> [error] Not a valid key: gen-idea
> [error] gen-idea
> [error]

**Comment by jozic** [comment]
what does your "about" command return?

**Comment by guersam** [comment]
have you included sbt-idea as sbt plugin instead of project dependency?

**Comment by mpeltonen** [comment]
As @jozic said, check what 'about' command tells you. In which file you have declared the plugin?

**Comment by gaoyike** [comment]
> about
> [info] This is sbt 0.12.0
> [info] The current project is {file:/Users/Readman/Desktop/lift-akka-sample-master/}default-8c0dad
> [info] The current project is built against Scala 2.9.2
> [info] Available Plugins: org.sbtidea.SbtIdeaPlugin, com.github.siasia.PluginKeys, com.github.siasia.WarPlugin, com.github.siasia.WebPlugin, com.github.siasia.WebappPlugin
> [info] sbt, sbt plugins, and build definitions are using Scala 2.9.2

plugin is in build.sbt

**Comment by mpeltonen** [comment]
I'm out of ideas if SbtIdeaPlugin is listed as available but 'gen-idea' is not found.

**Comment by jayded** [comment]
I also have this issue:

name := "hmm"

version := "0.1"

scalaVersion := "2.10.2"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.2")

resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

sbt update # successful

sbt gen-idea
Loading /usr/share/java/sbt/bin/sbt-launch-lib.bash
[info] Set current project to hmm (in build file:/home/jay/Dropbox/Documents/Semester%207/nlp/hw6/)
[error] Not a valid command: gen-idea
[error] Not a valid project ID: gen-idea
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: gen-idea
[error] gen-idea
[error]

**Comment by jozic** [comment]
@jayded 
plugins for you project should be declared in `<project_dir>/project/plugins.sbt`
see http://www.scala-sbt.org/release/docs/Getting-Started/Using-Plugins for details

**Comment by jozic** [comment]
@gaoyike 
could it be same issue for you? I see you have SbtIdea listed as a plugin, but maybe you have old typesafe's version which had same name but used `idea` instead of `gen-idea`
