### ISSUE TITLE
Additional test folder 

### ISSUE THREAD

**Issue by xerial** [mpeltonen/sbt-idea#215]
I am using sbt-multi-jvm plugin, and it uses src/multi-jvm/scala folder for its test code location as well as src/test/scala.
https://github.com/typesafehub/sbt-multi-jvm

I think there should be some sbt option for adding test code folders to the classpath, but I couldn't find how to do it.

Is there any option for adding test folders in sbt-idea so that the generated idea project file includes `src/multi-jvm/scala` as a test code folder?

**Comment by mpeltonen** [comment]
Do you mean as source folder? Would this work:

``` code
unmanagedSourceDirectories in Test <+= (baseDirectory) { _ / "src" / "multi-jvm" / "scala" }
```

**Comment by xerial** [comment]
Thanks! It works as expected.
