### ISSUE TITLE
Feature Request: Attach a Documentation URL to Dependencies

### ISSUE THREAD

**Issue by sirthias** [mpeltonen/sbt-idea#22]
IDEA supports adding a Documentation URL to dependency libs, a great feature that allows you to move the cursor over any class or method and press Shift-F1 to open a browser at the corresponding API doc page.
So far this only works for Java classes/methods, for some reason the Scala plugin doesn't open attached ScalaDoc API pages (yet). Still, it'd be nice if it was possible to somehow attach a Doc URL to a dependency in the SBT project definition, which the plugin would then convert into the respective IDEA setting.
I'm missing this for example with joda-time (http://joda-time.sourceforge.net/api-release/index.html).

**Comment by ijuma** [comment]
This sounds like a good idea. Shouldn't the part about attaching a Doc URL to a dependency in the SBT project definition be done in sbt proper though? The plugin part would then be just about using that information to configure the IDEA project.

**Comment by sirthias** [comment]
Yes, ideally SBT would provide a facility for doc url attachment.
However, seeing that you guys move at a much faster pace than the SBT devs maybe there is some short-term workaround solution you can think, which would already make the feature available, even though SBT proper is not there yet...

**Comment by mpeltonen** [comment]
Good suggestion. I wasn't aware of this kind of support in Idea. 

While the doc url attachment support should preferably be in sbt proper, I spiked this and ended up committing. In project definition you can now do:

import IdeaDocUrl._
val jodaTime = "joda-time" % "joda-time" % "1.6.2" withSources() ideaDocUrl("http://joda-time.sourceforge.net/api-release/")

And given doc url gets configured for Idea.

One downside for this not being in sbt proper is that you have to depend on the plugin and can't use just the processor version if you want to use this feature. But it's now an option anyways.

**Comment by sirthias** [comment]
Mikko,
this is great, thanks a lot for your continued determination to really drive this "sbt-idea" integration project home!!! You guys really move quickly!
Meanwhile I cannot find a reason NOT to use the plugin anymore...
It now enables me to drive the dependency setup of my IDEA project completely from the SBT side of things... excellent!!
Thanks a lot again for making this available!
Cheers,
Mathias

**Comment by mpeltonen** [comment]
I noticed that sbt has a way to add arbitrary extra attributes into dependency artifact like this:

 val jodaTime = "joda-time" % "joda-time" % "1.6.2" extra("docUrl" -> "http://joda-time.sourceforge.net/api-release/")

This would be a better way to specify the url, since it would't require dependency on the plugin and would also work with the processor. I'll explore this option further when I have more time.

**Comment by mpeltonen** [comment]
I changed this now to use the sbt's built-in extra("docUrl" -> "http://...") syntax. Update your project definition(s) when updating snapshot.

**Comment by mpeltonen** [comment]
Closing.
