### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by java-developer** [mpeltonen/sbt-idea#222]
Hello,

Thank you for creating this incredibly useful plugin!

My issue occurred with Scala 2.10.1 and SBT 0.12.3.

I think you should change the command in your README from

```
gen-idea
```

to

```
gen-idea no-sbt-build-module
```

as the former generates two modules which I can't imagine anyone would want. I lost a day battling with this until I found a comment on ticket https://github.com/mpeltonen/sbt-idea/issues/180

I would hate anyone else to have the same problem and give up.

Thanks!

**Comment by mpeltonen** [comment]
> which I can't imagine anyone would want

Well, I for one want to have the SBT build definition module visible in Idea for editing. Is it the most sensible default is debatable and depends on who you ask :)

**Comment by java-developer** [comment]
Fair enough. It was just a suggestion after some wasted time for me :)

**Comment by mpeltonen** [comment]
But you're definitely right in that those command line options should be in readme. Will improve that!
