### ISSUE TITLE
Why sbt-idea doesn't use scalacOptions key value when generating files?

### ISSUE THREAD

**Issue by Rogach** [mpeltonen/sbt-idea#235]
For example, I have the following contents in `build.scala`:

``` scala
import sbt._
import Keys._
object build extends Build {
  lazy val root = Project(id = "main", base = file(".")).settings (
    scalaVersion := "2.10.2",
    scalacOptions ++= Seq(
      "-deprecation",
      "-unchecked",
      "-optimize"
    )
  )
}
```

Running `gen-idea` gives me this (in `.idea_modules/main.iml`):

``` scala
        <option name="compilerOptions" value="-deprecation -unchecked"></option>
```

I am using scala `2.10.2` and sbt `0.12.3`. Why it doesn't output `-optimize` option into that file?

**Comment by Rogach** [comment]
Using snapshot version of sbt-idea (`1.5.0-SNAPSHOT`) or adding scope to `scalacOptions` (`scalacOptions in Compile`) didn't help.

**Comment by mpeltonen** [comment]
'Optimize bytecode' is separate checkbox in Scala Facet's configuration, and it is also stored as separate option, not as part of 'compilerOptions'. 

See option mappings here: https://github.com/mpeltonen/sbt-idea/blob/sbt-0.12/src/main/scala/org/sbtidea/IdeaModuleDescriptor.scala#L144-L149

**Comment by mpeltonen** [comment]
I.e. your configuration should be just fine, and you should get 'Optimize bytecode' checked in Scala Facet after gen-idea.

**Comment by mpeltonen** [comment]
Closing this as I think this should work correctly. Reopen if you find that it doesn't!

**Comment by Rogach** [comment]
I updated to `1.5.1`, but `optimizeBytecode` still is not present in any .idea\* files (and the checkbox is not becoming checked due to that). The same stuff happens for `-language:*` flags.

Github doesn't let me reopen the issue :) Should I open a new one?

**Comment by mpeltonen** [comment]
Hmm, the flag name is actually `-optimise`, -not `-optimize`. The former seems to work?

Language flags don't currently work, yes, as sbt-idea will only add options known to it (i.e. the ones in the Map:  https://github.com/mpeltonen/sbt-idea/blob/sbt-0.12/src/main/scala/org/sbtidea/IdeaModuleDescriptor.scala#L144-L149). 

I think that this restriction is not mandatory and should be removed so that all "unknown" flags would work. I'll reopen the issue for that.

**Comment by Rogach** [comment]
Wow, good catch! Why didn't scalac throw an error on unknown option (`-optimize`), though?

**Comment by mpeltonen** [comment]
I guess `-optimize`never got into compiler because it was filtered away with current implementation of sbt-idea (if you didn't try that flag with scalac directly?).

**Comment by Rogach** [comment]
I used that flag directly with sbt (without idea). Actually, I still use it :)

**Comment by mpeltonen** [comment]
> I used that flag directly with sbt (without idea). Actually, I still use it :)

Ah, so does scalac work with both then? Usage text says optimise anyway.

**Comment by mpeltonen** [comment]
You can now try other flags like -language:\* with the latest 1.6.0-SNAPSHOT.

**Comment by Rogach** [comment]
Thanks! I'll be able to test it tomorrow, and will report then.

**Comment by Rogach** [comment]
It works now. Thanks!
