### ISSUE TITLE
sbt 0.13.0-Beta2

### ISSUE THREAD

**Issue by huntc** [mpeltonen/sbt-idea#236]
Can you please provide an sbtVersion=0.13.0-Beta2, scalaVersion=2.10 compatible release? Thanks.

**Comment by retronym** [comment]
https://github.com/mpeltonen/sbt-idea/tree/sbt-0.13

I had to patch it with the following to avoid creating empty library descriptors

``` patch
~/code/sbt-idea git diff src/
diff --git a/src/main/scala/org/sbtidea/SbtIdeaModuleMapping.scala b/src/main/
index 38dee52..71c1bd9 100644
--- a/src/main/scala/org/sbtidea/SbtIdeaModuleMapping.scala
+++ b/src/main/scala/org/sbtidea/SbtIdeaModuleMapping.scala
@@ -7,8 +7,9 @@ object SbtIdeaModuleMapping {
   type JavadocClassifier = String

   def toIdeaLib(instance: ScalaInstance) = {
+    val patterns = Seq("compiler", "library", "reflect").map("scala-%s.*\\.ja
     val coreJars = instance.jars.filter { jar =>
-      Seq("compiler", "library", "reflect").map("scala-%s.jar" format _).exis
+      patterns.exists(pat => jar.getName.matches(pat))
     }.toSet
     val id = "scala-" + instance.version
     IdeaLibrary(id, "SBT: scala:" + instance.version, id, coreJars,
```

This is presumable a consequence of SBT now using Scala JARs directly from the Ivy Repository, as described: http://www.scala-sbt.org/0.13.0/docs/Community/ChangeSummary_0.13.0.html#resolving-scala-dependencies

**Comment by ijuma** [comment]
SBT 0.13.0 RC1 is now out so it would be great to have sbt-idea published for it.

**Comment by mpeltonen** [comment]
Latest snapshot published for sbt 0.13.0-RC1: https://groups.google.com/d/msg/simple-build-tool/wgMu0h6oxEs/wbH2_UqJJeAJ

**Comment by huntc** [comment]
Thanks @mpeltonen - which repo?

**Comment by ijuma** [comment]
If you follow the link, you'll see that it's Sonatype snapshots.

**Comment by huntc** [comment]
Sorry, I misread. I thought that there was an announcement here for the latest snapshot of the sbt-idea plugin.

**Comment by ijuma** [comment]
There was such an announcement and the instructions are in the link in @mpeltonen's message.

**Comment by ijuma** [comment]
Any chance that we can get a non-snapshot build? RC3 is now out[1] and RCs are meant to be binary compatible with final.

[1] http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/launcher/0.13.0-RC3/

**Comment by mpeltonen** [comment]
Absolutely. I'll do the stable build next weekend at the latest (It's a promise :)). I need to sync changes since last stable with 0.12 & 0.11 branches and do release notes so it requires some time.

**Comment by ijuma** [comment]
Awesome. Thank you!

**Comment by mpeltonen** [comment]
http://notes.implicit.ly/post/56635172083/sbt-idea-1-5-1

**Comment by ijuma** [comment]
Thanks!

**Comment by huntc** [comment]
Thank you!

**Comment by nafg** [comment]
Can you mention this in README.md (I guess update the Requirements section)?
Thanks!
