### ISSUE TITLE
Create IntelliJ module for parent project.

### ISSUE THREAD

**Issue by retronym** [mpeltonen/sbt-idea#24]
This would be in line with the project structure that IntelliJ generates from a multi-module Maven build. Without this, I can't see files in subdirectories of the parent project that don't correspond to a sub-module. The parent project should not have dependencies attached, nor should it have the Scala facet.

**Comment by mpeltonen** [comment]
Yes, a good idea. I also kind of realized this when discussing elsewhere about which directories to exclude from project view.

**Comment by mpeltonen** [comment]
Implemented in master.
