### ISSUE TITLE
Bug: IDEA library dependency not updated after a change on the SBT side

### ISSUE THREAD

**Issue by sirthias** [mpeltonen/sbt-idea#25]
I just experienced this:
I updated the version my TestNG dependency in the SBT project definition. Additionally I added an "withSources".
Then I ran "sbt update" and "sbt idea" to also refresh the IDEA library setting. However, the plugin did not touch the existing TestNG library configuration in the IDEA module settings.
I had to manually remove the now invalid entry in the module dependencies and run "sbt idea" again for the plugin to really create a new (updated) TestNG dependency.
I'm assuming the current behavior is a bit too conservative... the plugin only checks whether there is already an IDEA library configured for a dependency, but does not check the versions (and additional info like "withSources" or "ideaDocUrl"...

**Comment by mpeltonen** [comment]
No, it does not check that. It always creates the *iml files from scratch, why I'm kind of surprised of the behavior you were seeing. Is that repeatable?

**Comment by sirthias** [comment]
Hmm... strange. Something else must have prevented the update then...
I'll watch it closely the next time I encounter a dependency update.
Seeing as it might have been a problem specific to my setup I'll close the issue until then...
