### ISSUE TITLE
exclude some obvious directories

### ISSUE THREAD

**Issue by fommil** [mpeltonen/sbt-idea#259]
It would be great to automatically add Path Exclusion rules for a few obvious directories (so they don't show up in the Project view or get involved with VCS)
- `.idea`
- `.idea_modules`
- `project/target`

**Comment by jozic** [comment]
I've sent a similar PR #176 a year ago, but @mpeltonen wasn't sure sbt-idea needs this functionality.
If we can get enough votes for it I can resurrect my PR
