### ISSUE TITLE
Mislead to believe that sbt-idea can only be used with sbt 0.12.x

### ISSUE THREAD

**Issue by johannesschirrmeister** [mpeltonen/sbt-idea#261]
The requirements section in the README.md made me think that I need to downgrade to sbt 0.12.x in order to use this plug-in.

I'm still new to the world of Scala so maybe it is obvious to others that this plug-in can be used with sbt 0.13.x as well, but perhaps you could change it to "sbt > 0.12.x" or "sbt 0.12.x or newer".

Thank you so much for your efforts!

**Comment by mpeltonen** [comment]
The problem here is that there's currently separate branch of the plugin for different sbt versions, and hence, multiple READMEs. I now set the 0.13 branch to be the default, and added a link to 0.13 branch in 0.12 readme. I hope this helps to clear things out.
