### ISSUE TITLE
Android 4.3 Platform vs Android API 18 Platform

### ISSUE THREAD

**Issue by stanch** [mpeltonen/sbt-idea#263]
For some reason, the platforms in my Android Studio are now called “Android API X Platform”, not “Android 4.X Platform”. This is version 0.2.13, can’t really say when and how it happened. Thus `gen-idea` produces erroneous SDK name. Right now I am not really sure how to fix this, perhaps jetBrains guys can shed some light on what was the watershed (no pun intented) version?

**Comment by mpeltonen** [comment]
Yeah, this seems to be changed at some point. This is now changed in master for the android-sdk-plugin (not for android-plugin).

**Comment by longliveenduro** [comment]
In which version is this fix present>? I've tried 1.7.0-SNAP with android-sdk-plugin 1.2.14 and the bug is still present, see https://github.com/pfn/android-sdk-plugin/issues/51

**Comment by mpeltonen** [comment]
This is since 1.6.0 and is working fine for me (also with 1.7.0-SNAPSHOT). You could try the following (if not tried already):
- Close IntelliJ so that it is not running
- remove .idea and .idea_modules directories under your project dir
- run 'gen-idea'
- Start IntelliJ

**Comment by longliveenduro** [comment]
Thanks for the hint. I've tried it already but without success. The interesting thing is that gen-idea generates an entry "Android API -1 Platform". Do you have an clue why "-1"? Thanks in advance, Chris

**Comment by mpeltonen** [comment]
Have you set platformTarget in your sbt settings (e.g. platformTarget in Android := "android-18")?

What output do you get from this:

``` code
$ sbt "show android:targetSdkVersion"
```

**Comment by longliveenduro** [comment]
Yes I've set the option:
`platformTarget in Android := "android-19"`

```
chris@chris:~/prj/android/android-app$ sbt "show android:targetSdkVersion"
[info] Loading global plugins from /home/chris/.sbt/0.13/plugins
[info] Loading project definition from /home/chris/prj/android/android-app/project
[info] Set current project to gutefrage.net Android App (in build file:/home/chris/prj/android/android-app/)
[info] -1
```

**Comment by longliveenduro** [comment]
My complete build.sbt looks like this:

```
// so we can use keywords from Android, such as 'Android' and 'proguardOptions'
import android.Keys._

// load the android plugin into the build
android.Plugin.androidBuild

name := "gutefrage.net Android App"

// pick the version of scala you want to use
scalaVersion := "2.11.0"

// for non-ant-based projects, you'll need this for the specific build target:
platformTarget in Android := "android-19"

// call install and run without having to prefix with android:
run <<= run in Android

install <<= install in Android

libraryDependencies ++= Seq(
  "org.springframework.android" % "spring-android-core" % "1.0.1.RELEASE",
  "org.springframework.android" % "spring-android-rest-template" % "1.0.1.RELEASE",
  "com.google.code.gson" % "gson" % "2.2.4",
  "org.scaloid" %% "scaloid" % "3.3-8"
)

apkbuildExcludes in Android ++= Seq(
  "META-INF/notice.txt",
  "META-INF/license.txt"
)

proguardOptions in Android ++= Seq(
  "-dontwarn org.simpleframewok.xml.**",
  "-dontwarn org.springframework.http.converter.xml.**",
  "-dontwarn com.fasterxml.**",
  "-dontwarn org.codehaus.jackson.**",
  "-dontwarn com.google.code.rome.**",
  "-dontwarn org.apache.commons.**"
)

scalariformSettings
```

**Comment by mpeltonen** [comment]
Well, the problem is that android:targetSdkVersion seems to be -1 in your project, but I don't immediately see why from the build.sbt. In my build the "show" command returns 18, and I have very similar build.sbt.

What version of android plugin you have? Maybe something's changed in this regard?

**Comment by longliveenduro** [comment]
You mean version of the android-sdk-plugin? It's 1.2.14

Here's my plugins.sbt:

```
addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.2.14")

resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.7.0-SNAPSHOT")

addSbtPlugin("com.typesafe.sbt" % "sbt-scalariform" % "1.3.0")

```

I didn't find a build of 1.3-SNAPSHOT so far...

**Comment by longliveenduro** [comment]
Ah....just did a test and added 

```
    <uses-sdk
            android:minSdkVersion="14"
            android:targetSdkVersion="19"/>
```

to my AndroidManifest.xml and now 'sbt "show android:targetSdkVersion"' shows 19.

Do I still need the version in AndroidManifest.xml?
