### ISSUE TITLE
Output path is shared between modules on multimodule project with .sbt file for a module

### ISSUE THREAD

**Issue by kostaskougios** [mpeltonen/sbt-idea#271]
Hi, I have a multimodule project, one of the modules is a play module. I know the correct way to have multi-module projects is to have only 1 .sbt file for the root module but the play project is not happy with that and requires it's own .sbt file.

So currently my project has:

root-
    | build.sbt (A)
    | --- core (module)
    | --- helloworld (play module)

(A) looks like:

import play.Project._

name := "project"

version := "1.0"

// ----------------------------------------------------------------------
// child projects
// ----------------------------------------------------------------------

lazy val core = project.settings(
  libraryDependencies ++= {
...
  }
)

lazy val helloworld = project.settings(
  libraryDependencies ++= Seq(
...
  )
).dependsOn(core)

But also helloworld has an sbt file which is copied below:

name := "helloworld"

version := "1.0"

play.Project.playScalaSettings

But I end up getting the following error when I "gen-idea" and do a clean build from within intellij:

scala: Output path /home/ariskk/idea-workspace/project/project/target/idea-test-classes is shared between: Module 'helloworld-build' tests, Module 'project-build' tests
Output path /home/ariskk/idea-workspace/project/project/target/idea-classes is shared between: Module 'helloworld-build' production, Module 'project-build' production
Please configure separate output paths to proceed with the compilation.
TIP: you can use Project Artifacts to combine compiled classes if needed.

Is there a work around for this? Please note that without the helloworld/build.sbt, the play module is not working. 

Also all modules build/run ok within sbt.

Thanks

**Comment by kostaskougios** [comment]
Found the way to configure play module without a .sbt and the problem is no more for my project

**Comment by grahen** [comment]
I'm facing the same problem here, how did you proceed to configure the project without a .sbt?

**Comment by kostaskougios** [comment]
```
the problem was caused by the .sbt file
  for the play module. Sbt was fine with it but idea wasn't. I
  managed to configure all modules in the parent project's sbt file.
  On 13/01/14 14:19, grahen wrote:

  I'm facing the same problem here, how did you proceed to
    configure the project without a .sbt? 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by grahen** [comment]
Alright, probably I need to refactor the project definition. Currently I have just added a subproject with a .sbt file directly under a play project, thus I don't really have a parent sbt file, only the project/Build.scala file.

**Comment by kostaskougios** [comment]
```
I see, yes I think if you configure it
  in your play's sbt file, intellij should be happy
  On 13/01/14 14:46, grahen wrote:

  Alright, probably I need to refactor the project definition.
    Currently I have just added a subproject with a .sbt file
    directly under a play project, thus I don't really have a parent
    sbt file, only the project/Build.scala file. 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by grahen** [comment]
=(, seems getting rid of the sub projects .sbt file, i.e. defining the project in the Build.scala of the play app didn't help. Same error after gen-idea, i.e. that -build projects are sharing the output path.

**Comment by dawrut** [comment]
Don't know if relevant but the problem reproduces when one changes modules definition.
i.e. you change module id, then IntelliJ says that output path of new-named module is shared between old-named module.
Easy fix is to delete all target and .idea directories but it is more like forcing tool rebuild its project knowledge.
