### ISSUE TITLE
1.5.3 version with IDEA source dirs fix

### ISSUE THREAD

**Issue by nau** [mpeltonen/sbt-idea#275]
Hi. Could you please release a 1.5.3 version for sbt 0.12 and 0.13 with IDEA source dirs fix https://github.com/mpeltonen/sbt-idea/commit/194f7b714a286644146d610bd60f87a4ed23a2b7 ?
We have to use 1.6.0-SNAPSHOT and that slows down our build time. This would help us a lot. Thank you!

**Comment by BardurArantsson** [comment]
+1

**Comment by peregin** [comment]
+1 would be really cool

**Comment by mpeltonen** [comment]
I'll try to get this done over the weekend.

**Comment by OlegYch** [comment]
and https://github.com/mpeltonen/sbt-idea/pull/260 please

**Comment by mpeltonen** [comment]
Yes, it's already merged so it will be included.

**Comment by mpeltonen** [comment]
Release done. I chose version 1.6.0, though, as the changes we not just bug fixes: http://notes.implicit.ly/post/76027474730/sbt-idea-1-6-0

**Comment by BardurArantsson** [comment]
Thank you!

**Comment by nau** [comment]
Thanks!
