### ISSUE TITLE
1.6.0 with sbt 0.12.3  requires manual removal of .idea*

### ISSUE THREAD

**Issue by yonigoldberg** [mpeltonen/sbt-idea#283]
We are using sbt 0.12.3, and since we upgraded to 1.6.0 from 1.3.0, Intelij is not able to resolve the classpaths of the dependencies just by running 'sbt gen-idea'. 

The manual resolution to fix it is to:
- Exit Intllij
- rm -rf .idea*
- sbt gen-idea

**Comment by yonigoldberg** [comment]
Version 1.5.2 works, so it seems to be a bug in 1.6.0

**Comment by gbasler** [comment]
:thumbsup: I noticed that too. After I upgraded to 1.6.0, every time I add a new library and run `gen-idea` the new dependency is not addded...

**Comment by OlegYch** [comment]
could it be this http://youtrack.jetbrains.com/issue/IDEA-121781 ?

**Comment by gbasler** [comment]
I noticed that the new dependencies are actually added by the plugin, also outdates jars are removed. However, Intellij restored the old content of the libraries folder, when the project is reloaded. Try for yourself. I could not believe this when I figured it out... (look at the libraries folder, press reload and watch how intellij restores the content...)
