### ISSUE TITLE
Adding Dependencies Doesn't Update Properly

### ISSUE THREAD

**Issue by darkfrog26** [mpeltonen/sbt-idea#286]
Very often when I add a dependency (ScalaTest for example) after I've already generated the IntelliJ project files I expect it would properly update the project, but it does not and the dependency is unable to be found.  Ultimately the only way to fix my problem is by deleting the .idea and .idea_modules directories and running gen-idea again to get it to fix the dependencies.

I'm not sure if this is applicable to the problem, but I mostly run multi-project builds.  I've verified this is still a problem on 1.7.0-SNAPSHOT.

**Comment by jozic** [comment]
latest version should delete old libs for you, the only issue here is that if IntelliJ is running it will probably not allow libs to be deleted.

**Comment by OlegYch** [comment]
perhaps related to this http://youtrack.jetbrains.com/issue/IDEA-121781 ?

**Comment by darkfrog26** [comment]
It would seem my problem is directly related to leaving IntelliJ open.  If I close it before generating then it seems to work fine.

**Comment by jpswain** [comment]
@jozic @darkfrog26 just had the same issue trying to add scalatest.  running gen-idea with idea closed was a big help :-)
