### ISSUE TITLE
Edit, rather than overrwrite, .idea/misc.xml

### ISSUE THREAD

**Issue by retronym** [mpeltonen/sbt-idea#29]
Currently I need to revert changes made to .idea/misc.xml each time I re-run 'idea' to preserve manually entered project configuration that ends up in this file.

This is easy to forget, and requires a second project reload.

RewriteRule and RuleTransformer might be useful to implement this: http://stackoverflow.com/questions/970675/scala-modifying-nested-elements-in-xml/1306415#1306415

**Comment by mpeltonen** [comment]
I knew this would come up sooner or later :) But yes, preserving files would be much better approach and now we have someone actually needing that. And thanks for the RewriteRule/RuleTransformer tip! Wasn't aware of those.

**Comment by ijuma** [comment]
Indeed, this file seemed like a potential issue when I converted the code to use the directory-based format. If I recall correctly, it was the only file that seemed to include more things than what the plugin would configure.

**Comment by mpeltonen** [comment]
This is now implemented in master. Test 0.2-SNAPSHOT and see if it works for you.

**Comment by mpeltonen** [comment]
Closing.
