### ISSUE TITLE
The SBT project definition should not be a module in the IDEA project

### ISSUE THREAD

**Issue by hseeberger** [mpeltonen/sbt-idea#3]
When building the project in IDEA I don't want to build the SBT project definition. At least not in most cases => Remove the sbt_project_definition module or make it optional defaulting to "not a module"

**Comment by mpeltonen** [comment]
Generation of SBT build definition can now be disabled by adding idea.include.sbt.project.definition.module=false in project/build.properties. I left the default still to be true, because some folks (including myself :) like this to be the default.

**Comment by ijuma** [comment]
For what is worth, I agree with this. I also like the current default.

**Comment by hseeberger** [comment]
Thanks for the quick "fix". Could you please enlight me what's the use of having the project definition an IDEA module? Just to be sure, you don't misunderstand me: You can open and edit the project.scala and plugins.scala without creating a module.

**Comment by mpeltonen** [comment]
Yes you can, but then you don't have all the project definition dependencies (for example SBT itself, or any other 3rd party libraries you may be using in your  project definition) set up for you, and thus you will not be able to compile project definition and also miss autocompletion, auto import etc. ide goodies.

**Comment by hseeberger** [comment]
Well, for me I am doing fine without these goodies for the project definition, but now I understand your reasons.

After looking at your solution: I find it unusual to edit the build.properties file. Most plugins are configured by overriding a def or val. Is there a particular reason why you chose that way?

**Comment by mpeltonen** [comment]
Probably the main reason was at first just to explore the way properties can be used in sbt. But you're right, val/def override would be more common way of configuring a plugin and I will probably revert to using that.

**Comment by memelet** [comment]
For me at least, the sbt project file does not compile because the sbt jars are not added to the module. Hence I have to manually remove the module or exclude the source dirs after each update.

**Comment by memelet** [comment]
Well, I should say that entires for sbt are added as module dependencies, but they do not exist. eg,

./project/boot/scala-2.8.0/org.scala-tools.sbt/sbt/0.7.4 

is a module dependency but does not exists on disk.

**Comment by memelet** [comment]
Hmm, seems the jars are not in the location sbt things they should be:

```
 ==== Scala-Tools Maven2 Repository: tried

      http://scala-tools.org/repo-releases/org/scala-tools/sbt/sbt_2.8.0/0.7.4/sbt_2.8.0-0.7.4.pom

      -- artifact org.scala-tools.sbt#sbt_2.8.0;0.7.4!sbt_2.8.0.jar:

      http://scala-tools.org/repo-releases/org/scala-tools/sbt/sbt_2.8.0/0.7.4/sbt_2.8.0-0.7.4.jar

    ==== Scala-Tools Maven2 Snapshots Repository: tried

      http://scala-tools.org/repo-snapshots/org/scala-tools/sbt/sbt_2.8.0/0.7.4/sbt_2.8.0-0.7.4.pom

      -- artifact org.scala-tools.sbt#sbt_2.8.0;0.7.4!sbt_2.8.0.jar:

      http://scala-tools.org/repo-snapshots/org/scala-tools/sbt/sbt_2.8.0/0.7.4/sbt_2.8.0-0.7.4.jar
```

**Comment by mpeltonen** [comment]
You probably tried to use scala 2.8 as the def.scala.version? Sbt 0.7.x does not support scala 2.8 as the version used by the sbt project definition. I.e. you have to use 2.7.7 as def.scala.version in project/build.properties. build.scala.versions can have 2.8.

**Comment by mpeltonen** [comment]
Closing the issue, as property currently exists to disable sbt project definition module generation.

**Comment by slorber** [comment]
Hello,

I didn't open a new issue because i'm not sure if I didn't do something wrong but for me the project definition module is not created and I can't figure out why.
Check that SO question: http://stackoverflow.com/questions/18816766/why-sbt-idea-doesnt-generate-the-idea-module-for-my-build-project
