### ISSUE TITLE
Don't create .idea/vcs.xml

### ISSUE THREAD

**Issue by RSchulz** [mpeltonen/sbt-idea#31]
To the best of my knowledge and understanding, SBT-IDEA has nothing to go on to create .idea/vcs.xml files and overwriting existing ones that may have been created or edited by IDEA is undesirable.

I would like to have this file not generated or altered by the plug-in.

**Comment by mpeltonen** [comment]
Now with directory based format we should probably drop the modification of existing vcs.xml altogether, yes!

But what's the problem with generating a new one if it does not exist, based on .svn or .git directory existence?

**Comment by RSchulz** [comment]
As I said, it doesn't really have enough to go on. Our SBT project is not at the top level of a git repository. Are you going to search upwards towards the root of the file system to find a .git directory?

**Comment by mpeltonen** [comment]
Ah, of course, didn't think of that :) I think there's no point in trying to search .git dir and not touching it if it exists is the way to go.

**Comment by mpeltonen** [comment]
Do not modify existing .idea/vcs.xml. Closed by bafb88fbea9910c9ff44ad2179eca9e2ec44fbe0.
