### ISSUE TITLE
Download sbt plugins' sources, too?

### ISSUE THREAD

**Issue by michalrus** [mpeltonen/sbt-idea#312]
It would be really cool, if we could Ctrl+click from `build.sbt` to original plugin sources, wouldn't it? Now it jumps to IDEA-decompiled `*.class` files.

**Comment by jozic** [comment]
have you tried `sbt-classifiers` param?

**Comment by michalrus** [comment]
@jozic, silly me, works, closing. Thank you. =)

(Why isn't this a default? Can I force it to be using some setting?)

**Comment by OlegYch** [comment]
add this 

```
alias gi= gen-idea sbt-classifiers 
```

to ~/.sbtrc
would be nice to have sbt-classifiers enabled by default though

**Comment by michalrus** [comment]
Thank you. =) +1 to the default.
