### ISSUE TITLE
Sbt-idea for scala 2.12

### ISSUE THREAD

**Issue by jbarros35** [mpeltonen/sbt-idea#333]
Sorry but I can't ask for help to anybody, my options exausted.

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\work\workspace\simple-scala-rest-example-master\project
[info] Updating {file:/C:/work/workspace/simple-scala-rest-example-master/project/}simple-scala-rest-example-master-build...
[warn]  module not found: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.7.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.7.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\user\.ivy2\local\com.github.mpeltonen\sbt-idea\scala_2.12\sbt_1.0\1.7.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea_2.12_1.0/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\user\.sbt\preloaded\com.github.mpeltonen\sbt-idea\1.7.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/user/.sbt/preloaded/com/github/mpeltonen/sbt-idea_2.12_1.0/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom
[warn] ==== Sonatype snapshots: tried
[warn]   http://oss.sonatype.org/content/repositories/snapshots/com/github/mpeltonen/sbt-idea_2.12_1.0/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom
[warn] ==== Sonatype releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/github/mpeltonen/sbt-idea_2.12_1.0/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT: not found

I'm using latest sbt release, unfortunately its using scala 2.12 and cannot change it there is any hope for this?

resolvers ++= Seq(
    "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/",
    "Sonatype releases"  at "https://oss.sonatype.org/content/repositories/releases/"
)

addSbtPlugin("com.github.mpeltonen" %% "sbt-idea" % "1.7.0-SNAPSHOT")

name := "rest"

version := "1.0"

scalaVersion := "2.11.11"

libraryDependencies ++= Seq(
    "io.spray" % "spray-can" % "1.1-M8",
    "io.spray" % "spray-http" % "1.1-M8",
    "io.spray" % "spray-routing" % "1.1-M8",
    "net.liftweb" %% "lift-json" % "2.5.1",
    "com.typesafe.slick" %% "slick" % "1.0.1",
    "mysql" % "mysql-connector-java" % "5.1.25",
    "com.typesafe.akka" %% "akka-actor" % "2.1.4",
    "com.typesafe.akka" %% "akka-slf4j" % "2.1.4",
    "ch.qos.logback" % "logback-classic" % "1.0.13"
)

resolvers ++= Seq(
    "Spray repository" at "http://repo.spray.io",
    "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/",
	"Local Maven Repository" at file("file:///C:/dev/.m2/repository").toURI.toASCIIString,	
)

**Comment by laaksonel** [comment]
@jbarros35 You shouldn't need sbt-idea plugin since it was included in official Scala plugin. Read the first answer from here: https://stackoverflow.com/questions/37685387/sbt-gen-idea-fails-trying-to-import-a-sbt-managed-project-topnotch-from-github

**Comment by jbarros35** [comment]
Well if its suposed inside in official something why it still doesn't compiles?
"C:\Users\Jose\.sbt\preloaded\org.scala-sbt\sbt\"1.0.3"\jars\sbt.jar"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\workspace\hello-slick-2.1\ScalaStudy\project
[info] Updating ProjectRef(uri("file:/C:/workspace/hello-slick-2.1/ScalaStudy/project/"), "scalastudy-build")...
[warn]  module not found: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.7.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.7.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Jose\.ivy2\local\com.github.mpeltonen\sbt-idea\scala_2.12\sbt_1.0\1.7.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea_2.12_1.0/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Jose\.sbt\preloaded\com.github.mpeltonen\sbt-idea\1.7.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Jose/.sbt/preloaded/com/github/mpeltonen/sbt-idea_2.12_1.0/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom
[warn] ==== Sonatype snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/github/mpeltonen/sbt-idea_2.12_1.0/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.mpeltonen:sbt-idea:1.7.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.github.mpeltonen:sbt-idea:1.7.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0) (C:\workspace\hello-slick-2.1\ScalaStudy\project\plugins.sbt#L3-4)
[warn]            +- default:scalastudy-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2383)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT: not found
q

C:\workspace\hello-slick-2.1\ScalaStudy>sbt
"C:\Users\Jose\.sbt\preloaded\org.scala-sbt\sbt\"1.0.3"\jars\sbt.jar"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\workspace\hello-slick-2.1\ScalaStudy\project
[info] Updating ProjectRef(uri("file:/C:/workspace/hello-slick-2.1/ScalaStudy/project/"), "scalastudy-build")...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to ScalaStudy (in build file:/C:/workspace/hello-slick-2.1/ScalaStudy/)
[info] sbt server started at local:sbt-server-8ae5196e97aa7fa1dc26
sbt:ScalaStudy> gen-idea
[error] Not a valid command: gen-idea
[error] Not a valid project ID: gen-idea
[error] Expected ':'
[error] Not a valid key: gen-idea
[error] gen-idea

It doesn't make any sense.

**Comment by jbarros35** [comment]
Forget about it, Intellij is very bug with scala yet, and it is VERY FRUSTRATING.
