### ISSUE TITLE
No maven repository version for running sbt under Scala 2.8.1.

### ISSUE THREAD

**Issue by sroebuck** [mpeltonen/sbt-idea#34]
If sbt is running using Scala 2.8.1 it tries to find the dependency:
   com.github.mpeltonen#sbt-idea-processor_2.8.1;0.1.0
which does not exist.

This is running under sbt 0.7.5RC0.

**Comment by mpeltonen** [comment]
Sbt 0.7.x does not support Scala 2.8 for project definition, so you should really have "def.scala.version=2.7.7" in your project/build.properties, which should solve the problem AFAIK.

**Comment by mpeltonen** [comment]
Closing.
