### ISSUE TITLE
Add dependencies as "jar directories" rather than "classes"

### ISSUE THREAD

**Issue by Synesso** [mpeltonen/sbt-idea#35]
Can the plugin add dependencies as "jar directories" rather than "classes"? This would circumvent the need for the idea target to be re-run when the dependencies change.

**Comment by mpeltonen** [comment]
This has already been discussed in issue 7: https://github.com/mpeltonen/sbt-idea/issues/closed/#issue/7. This would most probably be possible, but I'm not sure it would make for example attaching sources and javadocs to dependencies easier? Then again, I may be wrong.

**Comment by Synesso** [comment]
I see! I rarely need to work with sources, but do frequently change dependencies. Re-running the idea target and waiting for idea to re-index is no big deal. Having other configuration change on .idea/ rebuild is somewhat annoying, but I suppose there are better solutions to that problem.

Cheers
