### ISSUE TITLE
idea task resets my project SDK to Java 1.6 (which does not exist)

### ISSUE THREAD

**Issue by Synesso** [mpeltonen/sbt-idea#36]
When I run the idea task it resets my project SDK to Java 1.6. This does not exist in the project so all java references break until I fix up my project SDK again.

**Comment by mpeltonen** [comment]
Did you notice the 'project.jdk.name' configuration option in readme? Would setting that solve your problem, or is the overridden property something else?

**Comment by Synesso** [comment]
My apologies. I didn't. I stopped reading at "Usage as processor".

The properties file is a workable approach. My opinion is that it would be better to use defaults on project creation, but respect existing properties on project re-creation. I appreciate that this is more work for sbt-idea than dealing with a properties file, but it is better for the user. ... IMHO.

That said, happy to close. Thanks for the info.
