### ISSUE TITLE
Problems and Feature requests

### ISSUE THREAD

**Issue by tinybyte** [mpeltonen/sbt-idea#37]
I updated this plugin to the latest version and found it's very good crafted and useful.
Find some minor problems:
1. The scroll bar didn't go with the output window. when the output log is huge, I have to manually drag the scroll bar, can't keep an eye on the windows easily.
1. little feature request: color output, especially mark [ERROR] to red text.

**Comment by mpeltonen** [comment]
Hi,

It seems like you're referring to idea-sbt-plugin (https://github.com/orfjackal/idea-sbt-plugin/issues) instead of sbt-idea ?

**Comment by mpeltonen** [comment]
Closing.
