### ISSUE TITLE
Every run creates different files

### ISSUE THREAD

**Issue by jrudolph** [mpeltonen/sbt-idea#38]
So, far I found two problems where the plugins creates different idea metadata for each run. This instability leads to spurious reloads necessary and unclear diffs if the generated files are put under version control (even if this is not recommended usage).

As usual this comes from some information put into sets. I observed:
1. Dependencies are spit out in varying order
2. Dependencies are taken from different folders inside of lib_managed/scala_X/{provided, test, etc.}

**Comment by retronym** [comment]
+1 We version control the .idea folder and stability is very welcome

**Comment by mpeltonen** [comment]
Merged, thanks!
