### ISSUE TITLE
Also add options to exclude lib and .idea

### ISSUE THREAD

**Issue by hseeberger** [mpeltonen/sbt-idea#41]
This could either be added to the existing config option (which should be renamed then) or maybe as individual ones.

**Comment by sirthias** [comment]
+1
Actually it might be even better to allow for a custom list of exclusions to be specified in idea.properties.
For example, in our current project we still have a bunch of TestNG tests (run through ScalaTest), which TestNG ends up creating a "/test-output" directory for.
I would like to exclude that too.

**Comment by mpeltonen** [comment]
Add execluded.folders property for specifying a list of folders to be
excluded from Idea project view. Closed by 0e63a07b7165dd75b03687ce80b377f5b79d8bbe.

Removed exclude.libmanaged.folders property. Use
&#39;excluded.folders=lib_managed&#39; instead.

**Comment by sirthias** [comment]
Thanks for the fix, however, there is still a small problem with it:
We have a multi-module project, where the parent project itself is also an IdeaProject (we do this to see the sbt project and plugin definition in IDEA).
Now, the "excluded.folders" settings works great on the sub (module) projects but is ignored on the parent project.
Is there a way to fix this?

**Comment by mpeltonen** [comment]
Yep, I just forgot to add the exclusions in ParentProject iml generation. I'll create a new ticket an will fix. Thanks for notification!
