### ISSUE TITLE
Would be useful to be able to turn of Web Facet generation installation wide

### ISSUE THREAD

**Issue by sroebuck** [mpeltonen/sbt-idea#42]
For those using the community edition of IntelliJ without web facets it would be useful if the processor could be set to not generate the web facet for web projects.

**Comment by mpeltonen** [comment]
Ah, you're correct. CE does not support web facets. 

Does it throw some error at you if you open a project with web facet defined?

**Comment by sroebuck** [comment]
It produces an error.  If you look at the error detail you are then offered the option of removing the facet which resolves the issue.  But if you are regularly updating the project with the (great :) ) sbt-idea processor then this can become a pain in the neck.

**Comment by mpeltonen** [comment]
Ok, seems like a good reason to do something about this. But as you say, it should be workstation based option, not project based, so we should use something like ~/.sbt-idea.properties.

**Comment by sroebuck** [comment]
Sounds good.  I guess the ideal would be that the interface could provide a mechanism for updating the properties file so that you don't have to know that it's there.  e.g.:

idea set web.facet false

or something broadly in keeping with the existing sbt setting mechanism.

**Comment by mpeltonen** [comment]
Add support for workstation-specific configuration (in ~/.sbt-idea file) and option to disable web facet generation for web projects, because Idea Community Edition does not support web facets. Closed by 8554ce59b8fb73a69a4f7c9d3fb68c7c880c2994.
