### ISSUE TITLE
Catch parse error of misc.xml, report that it is not well formed

### ISSUE THREAD

**Issue by retronym** [mpeltonen/sbt-idea#43]
If misc.xml is invalid XML (typically because it contains merge markers) and I run 'idea', a SAXParseException is reported. 

I suggest to catch exception and report an error with more context; and offer an option to blow away the existing file and recreate from scratch.

**Comment by mpeltonen** [comment]
Improve handling of non-well-formed misc.xml. Closed by d5dec977b87ec00c012347abc062eddbbcd8a1c2.
