### ISSUE TITLE
Dependencies "withSources"

### ISSUE THREAD

**Issue by omj** [mpeltonen/sbt-idea#44]
In sbt you can download dependency with source code via

val dep = "name" % "org" % "ver" withSources

It will be cool for plugin to pickup those sources to Idea.

**Comment by mpeltonen** [comment]
This should already work, i.e. sources should be configured correctly for Idea. Do you have an example where it doesn't work?

**Comment by omj** [comment]
Sorry, that was my mistake (not related to plugin)

**Comment by mpeltonen** [comment]
No problem!
