### ISSUE TITLE
Scala library should not be duplicated in multi-module projects

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#48]
Issue #32 handled the issue with user libraries. I believe we can do the same for the Scala library. Or is there a reason why this would not work?

**Comment by jrudolph** [comment]
Why would that be an advantage? I would think, since Scala is included as a library and that library is reused across the complete project there shouldn't be any double indexing.

Or what is your intention?

**Comment by ijuma** [comment]
Hmm, you're right. I thought I was getting duplicate entries when using "Open Class" for classes in the Scala library, but it part of it is because of buildScala versus defScala and the rest is due to the companion objects versus classes (it also didn't help that I used an example where there are many classes with the same name, HashMap). Closing.
