### ISSUE TITLE
too aggressively setting transitive dependencies as "TEST"

### ISSUE THREAD

**Issue by tackley** [mpeltonen/sbt-idea#50]
I've got the following dependencies in my project:

```
val slf4j = "org.slf4j" % "slf4j-api" % "1.6.0"
val slf4jsimple = "org.slf4j" % "slf4j-simple" % "1.6.0" % "test"
```

slf4j-simple has a transitive dependency on slf4j-api.

When I export to idea, both of these dependencies are marked as TEST:

```
 <orderEntry type="module-library" exported=" " scope="TEST">
  <library>
    <CLASSES>
      <root url="jar://$MODULE_DIR$/lib_managed/scala_2.8.1/test/slf4j-api-1.6.0.jar!/"></root>
    </CLASSES>
    <JAVADOC>


    </JAVADOC>
    <SOURCES>

    </SOURCES>
  </library>
</orderEntry><orderEntry type="module-library" exported=" " scope="TEST">
  <library>
    <CLASSES>
      <root url="jar://$MODULE_DIR$/lib_managed/scala_2.8.1/test/slf4j-simple-1.6.0.jar!/"></root>
    </CLASSES>
    <JAVADOC>


    </JAVADOC>
    <SOURCES>

    </SOURCES>
  </library>
</orderEntry>
```

They should not be. slf4j-api is a normal compile dependency.

**Comment by mpeltonen** [comment]
Could you test if the fix works for you?

**Comment by tackley** [comment]
Excellent, I've tried with 0.5.0-SNAPSHOT and it works fine, slf4j-api is correctly being created in the iml as compile scope.

However, I'm now seeing a very similar problem with "provided" dependencies, with the following dependencies:

```
val servletApi = "javax.servlet" % "servlet-api" % "2.5" % "provided" 
val jettyWebApp = "org.eclipse.jetty" % "jetty-webapp" % "7.2.2.v20101205" % "test"
```

(jetty-webapp depends on servlet-api 2.5). 

With just the servletApi dependency, servlet-api is included in the iml as `scope="PROVIDED"`. Adding the jettyWebApp dependency causes servlet-api to be included as `scope="TEST"`. It should still be provided scope.

I hadn't noticed this when I raised the initial issue, but I've just checked and I get this behaviour with 0.4.0 as well as 0.5.0-SNAPSHOT.

**Comment by mpeltonen** [comment]
Yep, I just filtered all "compile" dependencies from "test" classpath. The same should be done for "provided" and "runtime" dependencies. Will do.

**Comment by mpeltonen** [comment]
Did some more filtering. Does it work correctly now?

**Comment by tackley** [comment]
Yes, that's great, thanks!
