### ISSUE TITLE
Java Standard Libraries not found by Idea

### ISSUE THREAD

**Issue by scan** [mpeltonen/sbt-idea#59]
When I'm working with mixed code that uses Java AWT stuff, which rarely happens, I get the classes in red and Idea gives me tips all the time were to search for them. It compiles fine, but Idea regards them as errors, so it is quite annoying.

I've tried several ideas why that is happening, tried to invalidate cache etc. This does problem does not occur when I am making a non-sbt project. So I suspect that the sbt-idea plugin nicely and correctly adds the Scala deps to the project, but somehow omits the Java standard lib.

Could I be correct? I don't know enough about the workings of Idea's config files to tell. And if it is something else, sure tell me how to fix.

**Comment by mpeltonen** [comment]
One thing to check is that your JDK name in Idea matches the one ("1.6" by default) generated by sbt-idea. Check your project's "Module Settings" -> "SDKs" for what is the name of your JDK. If it is not "1.6", you can change it via sbt-idea setting "project.jdk.name" (see Configration in readme).

**Comment by scan** [comment]
Thanks, turned out I had no JDK in there at all, as I've only ever used Idea with your plugin since the reinstall. Keep up the good work!
