### ISSUE TITLE
What is buildScala?

### ISSUE THREAD

**Issue by mb-dev** [mpeltonen/sbt-idea#60]
I am new to sbt and this plugin. Tried it for the first time. When opening the generated .idea file inside IntelliJ I am getting that "please specify compiler in Scala facet". Now it's saying "buildScala" in red. 

How would I correct that?

**Comment by jeffcrilly** [comment]
Try closing your project, exiting intellij, restart intellij, and then open the sbt-idea-plugin created .idea project directory with intellij->file->Open_Project.

Seems to work.

**Comment by mb-dev** [comment]
Then please consider this as a feature request to either support generating a module and adding it to existing project.

Or provide written explanation how to make it work.

I believe it's a common scenario that we will want to have a single project with multiple scala modules

**Comment by mpeltonen** [comment]
Could you provide an example sbt project which does not open correctly in Idea after "sbt update" and "sbt idea" commands? And what version if Idea and Idea Scala plugin you are using?

**Comment by jeffcrilly** [comment]
Am using the latest 10.5 idea ultimate.   am using scala plugin 0.4.1041 (but just now I see there is a newer version 0.4.1084).
(and am just testing this with a "clean" environment.)

Let me clarify the project "opening" issue...

We use sbt 0.7.7 to create a project. 
sbt-idea:  idea is com.github.mpeltonen sbt-idea-processor 0.4.0

Am using sbt-idea as a processor, so "update" and "idea" to create the .iml files (and also the .idea directory)

Now, at this point assume the user already has an idea "project", e.g. an existing java project, and wants to add the new scala, sbt-idea created module, to that _existing_ project.
Also, assume that this existing project is _not_ the same as the one that sbt-idea "knows" about.

This is the problem.  My understanding is that sbt-idea creates the module, and would also needs to update the idea "project".
(I suspect there is a config, eg setting $PROJECT

@mb-dev is this is not your usecase scenario then please clarify.

Here's a test.
so I just recently fetched the akka source tree, which is a multi-module project.  
1) ran sbt-idea and it created a nice set of idea modules and a .idea project file for the whole akka project.  verified it looks good w/ idea.
2) removed one of the modules (eg akka-camel).
3) make sure there is no .iml file, and verify that idea doesn't see akka-camel any longer.
4) sbt

> project akka-camel // to switch to that project
> idea // to create the idea module.
> (.iml file for camel is created)
> In idea (note project is already open), do File->New_Module->Import-existing-module, and select the .iml file created in step 4.

Just works.

thx

**Comment by mpeltonen** [comment]
2011/5/29 jeffcrilly <
reply@reply.github.com>

> Now, at this point assume the user already has an idea "project", e.g. an
> existing java project, and wants to add the new scala, sbt-idea created
> module, to that _existing_ project.
> Also, assume that this existing project is _not_ the same as the one that
> sbt-idea "knows" about.
> 
> Ah, ok. This is definitely not currently supported. Sbt-idea overwrites
> .idea/modules.xml everytime with the modules of sbt project.

**Comment by mb-dev** [comment]
Thanks jeffcrilly, this is what I meant.

**Comment by mpeltonen** [comment]
Closing this. Please open new issue for further problems.
