### ISSUE TITLE
sbt-0.10 branch missed lib directory

### ISSUE THREAD

**Issue by leedm777** [mpeltonen/sbt-idea#61]
The version of this plugin for sbt-0.10 should add the ./lib directory as a Jar Directory.  This is really helpful in those (hopefully rare) occasions where one might need a patched version of a library, rather than relying on the version in a repository.

**Comment by retronym** [comment]
This should take actually take the contents of `unmanagedClasspath`.

**Comment by harrah** [comment]
I'm not sure what the question is or if it needs answering, but dependencyClasspath is the definitive source for the classpath for a project, excluding the products, as should be used for things like compilation/testing/running.  unmanagedClasspath is definitive for the non-managed classpath.  fullClasspath is definitive when the products of the project (compiled classes or packaged jar) are expected.

https://github.com/harrah/xsbt/wiki/Classpaths

**Comment by retronym** [comment]
This was fixed in https://github.com/mpeltonen/sbt-idea/commit/f73ee91a5d26e402d059fb1eb86a6059b586f98d

**Comment by ijuma** [comment]
Can we please close this since it's fixed as retronym said?
