### ISSUE TITLE
[sbt0.10] dependsOn(x) libraries not included in sbt-idea export

### ISSUE THREAD

**Issue by sroebuck** [mpeltonen/sbt-idea#62]
I have a simple project defined like this:

``` scala
    object MyBuild extends Build {
        lazy val myWebApp = Project("my-web-app", file(".")) dependsOn(myWebLibrary)
        lazy val myWebLibrary = RootProject(file("../my-web-library"))
    }
```

When I do a `gen-idea` on this the library "my-web-library" doesn't get included in the dependencies that are exported to IDEA.

I'm not sure if there could be an ivy component to this issue as if I then revert to removing this "dependsOn" and locally publishing the other project and explicitly adding it as a library dependency for the first, the problem persists until I cleared the local ivy cache and publish-local again.

**Comment by velvia** [comment]
I also have this problem.   The sources in the projects in dependsOn() do not get included.

**Comment by mpeltonen** [comment]
Latest snapshot should now support this. I (finally) cherry-picked a patch made by David Larsson (https://github.com/davidlar/sbt-idea/commit/ef170b8ad4803cd135e64799a3e56678e94598b0), which addresses this issue.

**Comment by mpeltonen** [comment]
Also notice that dependent project definition needs to have sbt-idea plugin configured too for this to work.

**Comment by mpeltonen** [comment]
Doh, I forgot to mention this issue in 1.0.0 release notes :(

**Comment by opyate** [comment]
> Also notice that dependent project definition needs to have sbt-idea plugin configured too for this to work.

Hi Mikko, does this hold for the case where I have sbt-idea configured globally in `~/.sbt/plugins/build.sbt` instead of explicitly for the dependent-on project?

**UPDATE**
Actually, it may be broken for me because my dependent-on project is multi-module. I'll create a re-producible test-case now and open a new issue if this is the case.

**Comment by mpeltonen** [comment]
That might well be the case with multi-module project, I haven't tried it. 

Yes, please open issue if you find reproducible case!

**Comment by opyate** [comment]
Done: https://github.com/mpeltonen/sbt-idea/issues/126

On 23 January 2012 16:00, Mikko Peltonen <
reply@reply.github.com
