### ISSUE TITLE
[0.10] Make with-classifiers and with-sbt-classifiers enabled by default

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#63]
Once SBT 0.10.1 is out, we should make them both enabled by default and remove the options. Instead, we should add -no-classifiers and no-sbt-classifiers to exclude dependency sources and Scala/SBT sources respectively.

I'll send a pull request with this once SBT 0.10.1 is out (some bugs in SBT 0.10.0 make this impractical).

**Comment by retronym** [comment]
Alternatively, we could rely on the setting of `transitiveClassifiers` and of (the new) `transitiveClassifiers in updateSbtClassifers`.

**Comment by ijuma** [comment]
This already happens if you use with-classifiers and with-sbt-classifiers (e.g. in my build, I only get sources, not javadocs). Another reason why it's the right default. Allowing users to override it while invoking the command is still a good idea and hence no-classifiers.
