### ISSUE TITLE
sbt-idea requires scala-lang be defined as a dependency in order for IDEA to resolve scala language.

### ISSUE THREAD

**Issue by plombardi89** [mpeltonen/sbt-idea#68]
It seems that sbt-idea requires I list the scala lang as a project dependency if I add any custom dependencies to my Build.scala. If I remove val scalalang = "org.scala-lang" % "scala-library" % "2.9.0-1" % "compile;runtime;test" from the below Build.scala IDEA will not find scala language symbols, constructs etc (they show up red).

``` scala
import sbt._
import Keys._

object BuildSettings { 
  val buildOrganization = "plombardi" 
  val buildScalaVersion = "2.9.0-1" 
  val buildVersion      = "0.0.1" 
  val buildSettings = Defaults.defaultSettings ++ Seq (organization := buildOrganization, scalaVersion := buildScalaVersion, version := buildVersion) 
}

object Dependencies {
  val scalalang = "org.scala-lang" % "scala-library" % "2.9.0-1" % "compile;runtime;test"
  val snakeyaml = "org.yaml" % "snakeyaml" % "1.8" % "compile"
}

object YabbsBuild extends Build {
    import BuildSettings._
  import Dependencies._

  val commonDeps = Seq (
    scalalang,
    snakeyaml
    )

    lazy val core = Project(
    "core", file("."), settings = buildSettings ++ Seq (libraryDependencies := commonDeps)
  )
} 
```

If I comment out the ++ Seq (libraryDependencies := commonDeps) from the Project def then the scala library is properly found by IDEA everything works as expected.

**Comment by retronym** [comment]
IDEA, and SBT, needs scala-library as a classpath dependency.

You should use:

`libraryDependencies ++= commonDeps`

as suggested in the SBT documentation.

**Comment by plombardi89** [comment]
That fixed it. I followed the full configuration example on the SBT wiki and they use =: ... I probably should have RTFM better though and the full example more closely; there must be something I missed.

Thanks though!

**Comment by retronym** [comment]
I've updated the Wiki.
