### ISSUE TITLE
Attach code to published jar

### ISSUE THREAD

**Issue by joaobsneto** [mpeltonen/sbt-idea#70]
I'm working on a multiple modules project and I would like to add dependencies with source folder attached to it in the idea project. The reason I want that is because when I debug the code and there is no reference to the other project source, the debugger uses the compiled jar.

**Comment by ijuma** [comment]
You have to describe your problem in more detail. What you describe should work (it works on my multi-module build). Mention what SBT version and sbt-idea versions you're using and perhaps an example build showing the issue.

**Comment by mpeltonen** [comment]
joaobsneto: Are you still having this problem and if yes, could you give a more detailed description with sbt-idea version etc.? If not, plz close the issue.

**Comment by joaobsneto** [comment]
Sbt version was 0.7.7, but I hadn't time to test enough to find where is the issue.
