### ISSUE TITLE
[0.10] project/plugins/project should not be excluded as a source path

### ISSUE THREAD

**Issue by retronym** [mpeltonen/sbt-idea#71]
This can contain, for example:

Build.scala

```
object build extends Build {
    lazy val sbtIdea = Project("root", file(".")) dependsOn(uri("git://git/zgg/sbt-idea#sbt-0.10"))
}
```

This file should be visible from IntelliJ.

**Comment by harrah** [comment]
I think the policy on default ignorable files that I will try to stick to with sbt is that the project/boot/ directory, any target/ directory, and any *_managed directory should be excluded (or cleaned, in other contexts).
