### ISSUE TITLE
Missing paths to sources in IntelliJ

### ISSUE THREAD

**Issue by rikvdkleij** [mpeltonen/sbt-idea#76]
Hi,

After running update-classifiers the sources of project library dependencies are retrieved. gen-idea only creates paths to the jars and not to source jars. Is this a known issue? Or do I forget something?

Regards,
Rik

**Comment by mpeltonen** [comment]
Try 'gen-idea with-classifiers'. That should do the trick.

**Comment by ijuma** [comment]
Also see #63

**Comment by rikvdkleij** [comment]
That works. Thank you very much for your quick reply.
