### ISSUE TITLE
[sbt-0.10.x] Excluded folder "target" hides $managed-sources-directories in "target/scala_x.y.z/src_managed"

### ISSUE THREAD

**Issue by gseitz** [mpeltonen/sbt-idea#78]
In sbt-0.10.x, managed sources end up in <project>/target/scala_x.y.z/src_managed.
And even though these folders are added to the module descriptors, they are still ignored by IntelliJ, since "target" is excluded by default.
IntelliJ then does not parse sources anywhere inside ./target/*\* and yields compile errors when compiling with IntelliJ (compiling with sbt works just fine).

**Comment by gseitz** [comment]
As this is actually an IntelliJ issue, feel free to close this issue, as the only real workaround seems to explicitely exclude every folder in target that's not part of managedSourcesDirectory.

**Comment by ijuma** [comment]
If this is the default for SBT, then something needs to be done somewhere. :) If this is an issue with other IDEs, maybe a case could be made in the SBT mailing list that the default should be different.

**Comment by teigen** [comment]
https://github.com/mpeltonen/sbt-idea/pull/84

**Comment by mpeltonen** [comment]
I merged teigen's fix into master some time ago. Could you please test if this works for you. 

The fix is currently only in 0.11.0-SNAPSHOT version.

**Comment by gseitz** [comment]
Works great, thanks.
