### ISSUE TITLE
Adding sbt-idea generated iml as module to Multi Module Intellj Project

### ISSUE THREAD

**Issue by bobymicroby** [mpeltonen/sbt-idea#79]
The problem is that the generated module will not find it's dependancies and the sbt console will not work at all.

How to reproduce.

After taking the standard path of creating a project and executing at the sbt console

*sbtIdeaRepo at http://mpeltonen.github.com/maven/
*idea is com.github.mpeltonen sbt-idea-processor 0.4.0
...
update
...
idea
...

we will end with generated iml file.

Open Intellj idea and click create a new project from scratch. Name it Master.
Click OFF the "Create Module" button and click Finish
When the project loads it will open it's Project Structure ( if on IDEA 10.5 ) if not open it manually (File->Project Structure) and select Modules . Click the + button to add a new module.
Select import existing module and locate the generated iml file.
You will see that the scala facet cannot find the buildScala dependancy and that the SBT console it is not working properly.

Regards, Bobby.

**Comment by mpeltonen** [comment]
This is not the way plugin is currently designed to work. The plugin generates the whole Intellij project (with settings for buildScala library etc.), and you have to open the whole project. You can't just pick generated iml -file to existing project.

**Comment by retronym** [comment]
If you really want to do this, you can probably just copy the generated `.idea/libraries/buildScala.xml` to the corresponding directory in your project.

**Comment by bobymicroby** [comment]
Alright, i will close the issue then.

**Comment by bobymicroby** [comment]
But what about the SBT console, it starts in the wrong directory. Any ideas?

**Comment by mpeltonen** [comment]
You're probably referring to this idea plugin: https://github.com/orfjackal/idea-sbt-plugin ?

No ideas, but I think that plugin may also require that your project is in the same directory as the sbt project?
