### ISSUE TITLE
Include resources and test-resources in classpath

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#8]
sbt includes resources and test-resources (in target) in the classpath when running classes. The way this is usually modelled in Eclipse is to also include them as output directories. IDEA, however, seems to only support two output directories and those are needed for classes and test-classes.

The only approach I have found is to include resources and test-resources directories as dependencies. I have a patch locally and I'll push it to my repository soon for review.

**Comment by ijuma** [comment]
Pushed commit to my fork:

http://github.com/ijuma/sbt-idea-plugin/commit/c4c6f9c23138acdf895b17bb13f5e4cc18106c68

**Comment by mpeltonen** [comment]
Tested and merged. Thanks!
