### ISSUE TITLE
0.10.1: Potentially incompatible versions specified

### ISSUE THREAD

**Issue by AlainODea** [mpeltonen/sbt-idea#80]
`Potentially incompatible versions specified` is reported in SBT with **sbt-idea** added to **~/.sbt/plugins/build.sbt** as follows:

``` scala
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

libraryDependencies += "com.github.mpeltonen" %% "sbt-idea" % "0.10.0"
```

It looks like a version numbering issue on the published Maven artifacts since the doc at https://github.com/mpeltonen/sbt-idea/tree/sbt-0.10#readme clearly says that 0.10.1 is required.

Looking at the Maven repo content through Github at https://github.com/mpeltonen/mpeltonen.github.com/tree/master/maven/com/github/mpeltonen/sbt-idea_2.8.1 shows that there are no artifacts for 0.10.1.

**Comment by AlainODea** [comment]
Doug Tangren suggests a solution in this topic on the SBT Google Group https://groups.google.com/d/topic/simple-build-tool/YoXd0Tp_cjo/discussion.

**Comment by mpeltonen** [comment]
Thanks for the report! I'll look into this asap.

**Comment by AlainODea** [comment]
My pleasure Mikko :)

**Comment by ijuma** [comment]
I added a comment to the mentioned thread. Republishing here:

"There are artifacts for 0.10.1. If you look at the pom:

```
    <dependency>
        <groupId>org.scala-tools.sbt</groupId>
        <artifactId>sbt_2.8.1</artifactId>
        <version>0.10.1</version>
        <scope>provided</scope>
    </dependency>
```

The fact that sbt-idea doesn't yet have cross-published builds for different sbt versions is an orthogonal issue (not so useful at the moment since 0.10.1 is required anyway). My guess is that you have another plugin that depends on 0.10.0."

**Comment by ijuma** [comment]
Also, sbt 0.10.2 will have an automated way of dealing with cross-publishing so I recommend waiting for that.

**Comment by mpeltonen** [comment]
Ok, thanks for the clarification Ismael. I was also kind of puzzled what this could mean, because the plugin is definitely built with 0.10.1. 

I also saw this when I had the old SNAPSHOT version declared.

**Comment by AlainODea** [comment]
I forgot to mention, but thanks Mikko.  Your fix works for me.  I no longer get the warning.  Much appreciated :)
