### ISSUE TITLE
Merge sbt-0.10 branch to master

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#81]
I think the sbt-0.10 branch should be merged to master and the current master should be moved to a sbt-0.7 branch. Many projects have already made the move and most new projects use sbt 0.10.x as far as I can see.

**Comment by mpeltonen** [comment]
Agreed & will do at my "asap" rate at the moment ;-)

**Comment by mpeltonen** [comment]
Done.
