### ISSUE TITLE
http://mpeltonen.github.com/maven/ returns a 404

### ISSUE THREAD

**Issue by dhinojosa** [mpeltonen/sbt-idea#82]
Nothing at the web address

**Comment by mpeltonen** [comment]
Directory listing is just not allowed. Direct links work (like http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.8.1/0.10.0/sbt-idea_2.8.1-0.10.0.jar).

Do you have some more specific sbt-idea related problem?

**Comment by dhinojosa** [comment]
Ah, ok, I was just used to see the directory tree for most resources to make sure I have it right.

**Comment by mtkopone** [comment]
Hi, 

I've used https://github.com/mtkopone/scct/blob/gh-pages/GenerateIndeces.scala to generate the indeces and then commit them into the gh-pages branch.

You're welcome to it.

**Comment by mpeltonen** [comment]
Ah, clever trick, thx for the tip!

**Comment by mpeltonen** [comment]
Added generated indices to the repo, after receiving enough 'error reports' via private mail :-). Thanks again for the script mtkopone!
