### ISSUE TITLE
Support SBT 0.11

### ISSUE THREAD

**Issue by ijuma** [mpeltonen/sbt-idea#88]
SBT 0.11 RC 0 has been released:

https://groups.google.com/d/topic/simple-build-tool/TEOjVzOwFOE/discussion

There have been some minor changes when it comes to plugins:

https://groups.google.com/d/topic/simple-build-tool/ep_63fA_Gzk/discussion

I have a branch with the necessary changes:

https://github.com/ijuma/sbt-idea/tree/sbt-0.11
https://github.com/ijuma/sbt-idea/compare/master...sbt-0.11

**Comment by mpeltonen** [comment]
Thanks! Current changes merged to master.

**Comment by channingwalton** [comment]
Hi, I'm keen to add this to our project. Is there going to be a release soon?

**Comment by ijuma** [comment]
I think we should wait until SBT 0.11.0 final before we do a final release. A snapshot release would be handy though.

**Comment by channingwalton** [comment]
yes, anything would be appreciated. Thanks

**Comment by mpeltonen** [comment]
I pushed a snapshot for 0.11.RC1 yesterday: http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.1_0.11.0-RC1/

**Comment by channingwalton** [comment]
Very cool. Thanks. 

-~-~-~-~-~-~-~-~-
Channing Walton

m: +44 (0) 7980 294 809
t: +44 (0) 1483 799 491

web:    http://www.casualmiracles.com/
twitter:    http://www.twitter.com/channingwalton

**Comment by channingwalton** [comment]
actually I can't figure out how to get sbt to find the plugin.

The url to the location of jars is http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.1_0.11.0-RC1/0.11.0-SNAPSHOT/

but the jar is sbt-idea-0.11.0-SNAPSHOT.jar

**Comment by eweise** [comment]
I am have the same issue trying to use the 11.0-SNAPSHOT.  What should the sbt dependency look like?

thanks

**Comment by mpeltonen** [comment]
Try adding line:

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0-SNAPSHOT")

into project/plugins.sbt

Further details: https://groups.google.com/d/msg/simple-build-tool/ep_63fA_Gzk/i3hjlhNpg5kJ

**Comment by channingwalton** [comment]
Thanks Mikko, that did it.

---

www.stateofflow.com   www.casualmiracles.com
http://www.twitter.com/channingwalton
+44 7980 294809

**Comment by mpeltonen** [comment]
Added 0.11RC install info also to readme.

**Comment by ijuma** [comment]
Mikko, now that SBT 0.11.0 is out, when do you plan to have a non-snapshot release of the plugin?

**Comment by mpeltonen** [comment]
Hopefully very soon (this week anyway).

**Comment by ijuma** [comment]
Great, thanks.

**Comment by irumiha** [comment]
I can not get this to work.

My ~/.sbt/plugins/build.sbt contains:

```
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0-SNAPSHOT")
```

What am I doing wrong?

**Comment by mpeltonen** [comment]
The correct file with sbt 0.11 is now ~/.sbt/plugins.sbt.

**Comment by irumiha** [comment]
Yes, I figured that one out eventually. :) Thanks!

**Comment by mpeltonen** [comment]
Release version published.
