### ISSUE TITLE
Don't attach the Scala Facet to the 'project' module

### ISSUE THREAD

**Issue by retronym** [mpeltonen/sbt-idea#92]
There is no reason to compile the build definition when selecting Build, Compile Project; removing the Scala Facet is the easiest way to achieve this.

Furthermore, it stops attempted compilation of the build.sbt files, see http://youtrack.jetbrains.net/issue/SCL-3616

Code completion, navigation etc still work as expected.

**Comment by mpeltonen** [comment]
Agreed. I've been even thinking if we should drop the whole build definition module altogether (I'm almost always editing it outside idea), but just removing the Scala facet would probably be better.

**Comment by ijuma** [comment]
I agree that removing the Scala facet would be good. Please don't remove the build definition module though, code navigation is very useful. :)
