### ISSUE TITLE
0.11.0 readme bug: wrong path for specifying plugin

### ISSUE THREAD

**Issue by adamw** [mpeltonen/sbt-idea#96]
See https://groups.google.com/forum/#!topic/simple-build-tool/aQSYQEc6ec8

The plugin should be added to ~/.sbt/plugins/build.sbt, not ~/.sbt/plugins.sbt

**Comment by mpeltonen** [comment]
Yep, issue #95 also told me that, and fixed it about the same time you created the issue :) Thanks for reporting anyway!
