### ISSUE TITLE
sbt resolving the wrong artifact path?

### ISSUE THREAD

**Issue by fernandezpablo85** [mpeltonen/sbt-idea#98]
Hey Mikko,

Wanted to try your plugin but with this directives:

``` scala

  resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

  libraryDependencies += "com.github.mpeltonen" %% "sbt-idea" % "0.11.0"

```

on ~/.sbt/plugins/build.sbt, sbt resolves the plugin path to:

  http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.1/0.11.0/sbt-idea_2.9.1-0.11.0.pom

When the actual plugin is on:

  http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea_2.9.1_0.11.0/0.11.0/sbt-idea_2.9.1-0.11.0.pom

(emphasis on the difference)

Do you know why this doesn't work out of the box?

Cheers!

**Comment by mpeltonen** [comment]
Use the format that is mentioned in readme for sbt 0.11:

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0")

This is the recommended way to declare plugins for sbt 0.11 and it includes the sbt version in path (which is missing from your version).

**Comment by fernandezpablo85** [comment]
Sorry. I'm an idiot

**Comment by josephks** [comment]
I ran into the problem also.  Perhaps this should be clearer in the README?
