### ISSUE TITLE
Modules should be set to use FSC

### ISSUE THREAD

**Issue by adamw** [mpeltonen/sbt-idea#99]
With the update Scala plugin, FSC finally works great. However, to enable it, a per-module switch must be set in the facet settings. After generating the idea project it is set to "Use ordinary compiler". It would be much better if there was at least an option to have "Use project FSC" set by default.

**Comment by mpeltonen** [comment]
Sounds like a good idea! Thanks for the info.

**Comment by miguel-negrao** [comment]
I agree !!

To do this the plugin should add in the .iml file this line in `<configuration>`:

``` xml
<option name="fsc" value="true" />
```

so:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="FacetManager">
    <facet type="scala" name="Scala">
      <configuration>
        <option name="compilerLibraryLevel" value="Project" />
        <option name="compilerLibraryName" value="scala-2.9.1" />
        <option name="fsc" value="true" />
```

**Comment by benjaminparker** [comment]
I am trying to implement this but first I need to get the scripted test to work.  It appears that the test relies on the temp directory to be /tmp - by default I get some crazy private/var/... path - any ideas how to set this temp dir - would be good if the test was agnostic or set this variable

**Comment by mpeltonen** [comment]
The scripted-thing sounds odd. There aren't any path requirements for scripted tests set in sbt-idea project, it just uses the scripted plugin's defaults, and I didn't quickly find any glues about /tmp -requirement from sources. One setting to try could be sbt-test-directory, see: https://github.com/harrah/xsbt/blob/0.11/scripted/plugin/ScriptedPlugin.scala

What OS are you running?

**Comment by benjaminparker** [comment]
I am on OSX.

I have solved the issue. OSX by default sets temp folder location to /var/folders/<some random looking folder path>

export $TMPDIR=/tmp/
clean all target folders in sbt-test

I'll have a look at getting the fsc setting working over the weekend

**Comment by mpeltonen** [comment]
Fix merged to master. Thanks Benjamin!
